### ISSUE TITLE
Issues needing to be fixed for deli

### ISSUE THREAD

**Issue by azatoth** [azatoth/twinkle#1]
* Make sure image is deleted before unlinking
* hide "invalid token" the first times

**Comment by atlight** [comment]
The plan from 30 March 2013 has finally come to fruition in 315c06b52db660176c8ff5489611a02c52f1ca1f. (Things don't happen quickly around here!)

If no-one objects in the next few months, I plan to delete the delimages module altogether.

@AzaToth's original concerns from 2011 should now both be fixed. Leaving this issue open, though, to track the removal of delimages.

**Comment by atlight** [comment]
a209b75f82deba8010dea639d4950aff9d2b2e86
