### ISSUE TITLE
Request: Allow merge nominations for pages in Project and Help spaces

### ISSUE THREAD

**Issue by sdkb** [azatoth/twinkle#1011]
There is currently no way (that I know of) to use Twinkle to nominate a Help: page or WP: page for merging with another page. (The article maintenance tags aren't available as they are for mainspace pages, and XfD doesn't have a merge component the way TfD does.) This is a significant issue, because there is extensive duplication of pages within those namespaces and [pressing need](https://en.wikipedia.org/w/index.php?title=Wikipedia:Village_pump_(policy)&oldid=965173479#Why_our_introductory_policy_pages_are_so_bad,_and_practical_steps_for_improving_them) to consolidate them; being able to easily propose a merge through Twinkle might help encourage that process.

**Comment by Amorymeltzer** [comment]
Closing per my comments on-wiki, which is where this sort of policy discussion should take place.

>WP:MfD if you must, just explain yourself in the summary. I don't have the link on-hand, but there was a discussion a little while ago about renaming MfD to ...for discussion (it comes up now and then); IIRC it was poorly attended but the general sense was that things that are MfD-eligible but not up for deletion should probably be discussed elsewhere.
At any rate, Twinkle doesn't dictate policy; if you'd like to change MfD procedure, I'd head over to WT:MfD or WP:VPP.

**Comment by Amorymeltzer** [comment]
I misunderstood the point of this.  This isn't about XfD, it's about enabling tag on more namespaces with a limited set of tags, namely the {{Merge-family.

**Comment by sdkb** [comment]
@siddharthvp let me know if I can assist with details or a plan in any way beyond what I wrote up top.

**Comment by sdkb** [comment]
@siddharthvp just quickly following up, could you clarify what "details or plan" are needed to move this forward that have not yet been provided?

**Comment by siddharthvp** [comment]
Well, plan about how to support more namespaces🙃. That can be discussed in a pull request also. There's nothing preventing this from moving forward. You or anyone else familiar with JS can contribute a patch.

**Comment by sdkb** [comment]
I'm unfortunately not familiar with JS myself. But I'd certainly be appreciative of anyone who decides to take this on.
