### ISSUE TITLE
Custom warnings produce broken edit summaries (undefined)

### ISSUE THREAD

**Issue by flori4nk** [azatoth/twinkle#1025]
When using a custom warning, _undefined_ is inserted into the edit summary instead of the value of _label_ ([Example Diff](https://en.wikipedia.org/wiki/Special:Diff/966836553)).
No warnings were shown and there's nothing new to be found in the console.

Warning definition:
```
"customWarningList": [
    {
      "value": "uw-webhost",
      "label": "Using Wikipedia as a web host"
    }
  ],
```

**Comment by Amorymeltzer** [comment]
Nice find — it's apparently specific to selecting custom modules when using the "All templates" menu.  I presume that's what you were doing?  Opened #1026, which should fix it, as well as another bug I found in doing so!

**Comment by flori4nk** [comment]
Yes, that's what I was using.
