### ISSUE TITLE
warn: Autolevel didn't set to 4 if previous warning is signlewarn

### ISSUE THREAD

**Issue by Xi-Plus** [azatoth/twinkle#1027]
Related code:
https://github.com/azatoth/twinkle/blob/07fffdf04bf8adf008862eb2ac2e5cc52c28b9d9/modules/twinklewarn.js#L1499-L1516
Level increased by 1 according to previous warning. But didn't do if previous warning is signlewarn.
If I understand correctly, ~L1508 should check `latest.type` instead of `template` (`params.sub_group`)~.

**Comment by Xi-Plus** [comment]
And there are some strange behavior.
Step to reproduce:
1. Give user a singlewarn warning
2. Open Twinkle Warn tool
3. Select "Single-issue notices"
4. Select "Auto-select level (1-4)"
5. You will see "Will issue a level 2 template."
6. Select "Single-issue warnings"
7. Select "Auto-select level (1-4)"
8. You will see "Will issue a level 4 template."
Repeat step 3-8. Twinkle suggest different levels without any new warning given.

**Comment by Amorymeltzer** [comment]
Yes I think that's right; PR comin' up!

**Comment by Amorymeltzer** [comment]
#1028
