### ISSUE TITLE
warn: Stale message may showing before form rendering

### ISSUE THREAD

**Issue by Xi-Plus** [azatoth/twinkle#1054]
If you pass the `vantimestamp` in url.
The stale message
https://github.com/azatoth/twinkle/blob/c338c26cc33ab12df0795465ac236d330f1c3a50/modules/twinklewarn.js#L146-L149
may showing before form rendering
https://github.com/azatoth/twinkle/blob/c338c26cc33ab12df0795465ac236d330f1c3a50/modules/twinklewarn.js#L185
So you will not see the stale message. Because `$('#twinkle-warn-warning-messages')` is undefined in L148.

**Comment by Amorymeltzer** [comment]
@Xi-Plus Assuming I understand you correctly, surprised I never ran into that!  That whole if should just be moved under the render, yeah?

Then again, maybe it could/should be refactored into `change_category`, where autolevel deals with some of that...

**Comment by Xi-Plus** [comment]
> That whole if should just be moved under the render, yeah?

@Amorymeltzer Yes. This can fix it.

**Comment by Amorymeltzer** [comment]
#1056 

> Then again, maybe it could/should be refactored into `change_category`, where autolevel deals with some of that...

This wasn't a good idea... 💤 💤 😴
