### ISSUE TITLE
tag: Stuck in "Adding supported tags inside existing {{multiple issues}} tag"

### ISSUE THREAD

**Issue by Xi-Plus** [azatoth/twinkle#1058]
If there is no "UngroupedTags", `tagText` is `""` in L1533.
https://github.com/azatoth/twinkle/blob/2b6f9a76a2cff95dd9d33c26a9beae416f318357/modules/friendlytag.js#L1515-L1536
And throw error in
https://github.com/azatoth/twinkle/blob/2b6f9a76a2cff95dd9d33c26a9beae416f318357/morebits.js#L4009-L4012

**Comment by Amorymeltzer** [comment]
Word.  You've fixed it on your end one way, I'm inclined to say that's not a bad idea.  I'm mixed on whether the lack of tag should throw or just `return this` ([doubting myself](https://github.com/azatoth/twinkle/pull/1022#discussion_r451509153)) but I suppose checking that they're actually provided is better than just `if (tagText)` in tag...

**Comment by Amorymeltzer** [comment]
Replicated in #1060
