### ISSUE TITLE
fluff: Hide the rollback links on the latest version in the history when all versions are made by the same user

### ISSUE THREAD

**Issue by Xi-Plus** [azatoth/twinkle#1062]
Hide "[rollback] [vandalism]" links, because rollback will fail.
You may be able to simply use the following code to check it.
```javascript
$.unique(
    $('.history-user').find('.mw-userlink:not(.history-deleted)').map(function(_, user) {
        return $(user).text()
    })
).length === 1
```
Sample pages:
https://en.wikipedia.org/w/index.php?title=Othana&action=history
https://en.wikipedia.org/w/index.php?title=User:Xiplus/sandbox&action=history

**Comment by Amorymeltzer** [comment]
Nice idea!  Might be quicker to use JS and push to an array, but I don't think it should take too much time overall unless someone's looking at 500, etc. revs at a time.

Couldn't we also just take that first username, then iterate over the list until we find one that doesn't match?  Might be faster.

**Comment by Xi-Plus** [comment]
> Couldn't we also just take that first username, then iterate over the list until we find one that doesn't match? Might be faster.

That's better!

**Comment by Amorymeltzer** [comment]
#1070
