### ISSUE TITLE
Twinkle.diff assumes the newer revision is always on the right

### ISSUE THREAD

**Issue by he7d3r** [azatoth/twinkle#107]
Although the newer revision is _usually_ on the right, it may also be on the left. Compare the value of the code [```var oldid = /oldid=(.+)/.exec($('#mw-diff-ntitle1').find('strong a').first().attr("href"))[1];```](https://github.com/azatoth/twinkle/blob/119909b2b4496dc0b6a10289c78c559d2036cde0/modules/twinklediff.js#L34) on these cases:
1) https://en.wikipedia.org/w/index.php?title=Example&diff=486460758&oldid=451042477
2) https://en.wikipedia.org/w/index.php?title=Example&diff=451042477&oldid=486460758

In the first case, it gets the id of the most recent but on the second it gets the id of the older revision.

**Comment by atlight** [comment]
I don't think anyone is going to ever fix this bug. I don't understand what the hell current/since/since mine are even supposed to do, and Amalthea thinks the current behaviour is OK...

@he7d3r, would you like to elaborate to help get to the bottom of this?

**Comment by he7d3r** [comment]
I guess it is working as intended then...
