### ISSUE TITLE
welcome: Automatically welcome send "undefined" template to user

### ISSUE THREAD

**Issue by Xi-Plus** [azatoth/twinkle#1079]
https://en.wikipedia.org/w/index.php?title=User_talk:A2093064-test2&oldid=970553584

https://github.com/azatoth/twinkle/blob/3c65fa5bf409143b99f0af3f4bddbb32a65b45ab/modules/friendlywelcome.js#L99
Change `value` to `welcome` to fix it.

See
https://github.com/azatoth/twinkle/blob/3c65fa5bf409143b99f0af3f4bddbb32a65b45ab/modules/friendlywelcome.js#L627

**Comment by Amorymeltzer** [comment]
`template`, but yes!  Didn't see this until responding to what was apparently the same issue at WT:TW, so done in #1080
