### ISSUE TITLE
[speedy] {{di-orphaned fair use}} includes |replacement=File: when no replacement is specified

### ISSUE THREAD

**Issue by JJMC89** [azatoth/twinkle#1107]
When adding `{{di-orphaned fair use}}` without a replacement specified, Twinkle erroneously adds `|replacement=File:`. ([example](https://en.wikipedia.org/w/index.php?title=File:Oswald_The_Lucky_Rabbit.svg&diff=prev&oldid=973199977))

**Comment by Amorymeltzer** [comment]
Line 184, from #908 / 75ac3850a
