### ISSUE TITLE
[tag] Cannot add {{should be SVG}} to PNG

### ISSUE THREAD

**Issue by JJMC89** [azatoth/twinkle#1108]
I tried to add `{{should be SVG|logo}}` in [this edit](https://en.wikipedia.org/w/index.php?title=File:Hick,_Hargreaves_logo.png&diff=prev&oldid=973203912) with `{{Opaque}}`, but Twinkle wouldn't let me.

```
This appears to be a png file, please use {{Should be PNG}} instead.
```

**Comment by Amorymeltzer** [comment]
I'm an idiot
