### ISSUE TITLE
Speedy deleted pages are not being added to watchlist

### ISSUE THREAD

**Issue by wiki-ST47** [azatoth/twinkle#1113]
According to my Twinkle settings, (which I have not changed recently), pages that I G5 are supposed to be added to my watchlist:

![image](https://user-images.githubusercontent.com/57046754/91648482-7b8a0d80-ea36-11ea-9a28-3dc59bc558b0.png)

However, this does not happen:

![image](https://user-images.githubusercontent.com/57046754/91648498-a3797100-ea36-11ea-8ab4-72301400ec56.png)

**Comment by wiki-ST47** [comment]
If I choose to "tag only", the page is added to the watchlist.

**Comment by Amorymeltzer** [comment]
AFAICT, Twinkle has been not doing this since 2016!
