### ISSUE TITLE
Missing token errors

### ISSUE THREAD

**Issue by siddharthvp** [azatoth/twinkle#1119]
Needs investigation. Been reported many times of late:

* https://en.wikipedia.org/wiki/Wikipedia_talk:Twinkle/Archive_43#Error_with_XfD
* https://en.wikipedia.org/w/index.php?title=Wikipedia:Articles_for_deletion/Ry%C5%8Dhei_Arai&diff=976224156&oldid=976219898&diffmode=source
* https://en.wikipedia.org/wiki/User_talk:SD0001/DYK-helper#This_script_lost_my_nomination (DYK helper uses morebits)

One would think https://github.com/azatoth/twinkle/pull/1038/commits/af13dcede0ec3452adf835c2baf597e25b4312a0 removed all possibility of token errors, but apparently not.

**Comment by Amorymeltzer** [comment]
The timing of one or two of these is weird, but I think there have recently been some server-side token issues (or, at least, others).  Good to have open to track.

**Comment by Amorymeltzer** [comment]
All these came after #1038 so I wonder if #1143 won't solve them all?

**Comment by siddharthvp** [comment]
Indeed it would.
