### ISSUE TITLE
[[WP:PB|blocked]]

### ISSUE THREAD

**Issue by ToBeFree** [azatoth/twinkle#1124]
Current Twinkle edit summary for issuing partial block notices on user talk pages:
`You have been [[WP:PB|blocked]] from editing certain areas of the encyclopedia`

Proposed replacement:
`You have been [[WP:PB|blocked from editing certain areas of the encyclopedia]]`

Reason: "Partial blocks" is a surprising target behind the "blocked" wikilink. The link text should make clear where the link points to.

**Comment by Amorymeltzer** [comment]
@ToBeFree Couldn't we just do `[[WP:PB|partially blocked]]` for 'em all?  It's a little clunky but better?

**Comment by ToBeFree** [comment]
Sure – I was just surprised about the current link. :)

**Comment by Amorymeltzer** [comment]
Indeed.  The problem is with things like

>You have been partially blocked from creating accounts for misusing multiple accounts

That sounds like you have been prevented somewhat from creating accounts, not that you've been prevented *only* from creating accounts.  So maybe the thing to do is:


```
1030:		summary: 'You have been [[WP:PB|blocked from creating accounts]] for misusing [[WP:SOCK|multiple accounts]]'
1040:		summary: 'You have been indefinitely [[WP:PB|blocked from creating accounts]] for misusing [[WP:SOCK|multiple accounts]]'
1048:		summary: 'You have been [[WP:PB|partially blocked]] from editing for violating an [[WP:Arbitration|arbitration decision]]'
1059:		summary: 'You have been [[WP:PB|blocked from emailing]] other editors for [[WP:Harassment|harassment]]'
1068:		summary: 'You have been [[WP:PB|partially blocked]] from editing certain areas of the encyclopedia to prevent further [[WP:DE|disruption]] due to [[WP:EW|edit warring]]'
1076:		summary: 'You have been [[WP:PB|partially blocked]] from certain areas of the encyclopedia'
1085:		summary: 'You have been indefinitely [[WP:PB|partially blocked]] from certain areas of the encyclopedia'
```

That is, `[[WP:PB|partially blocked]]` for editing/generic and `[[WP:PB|blocked from _restriction_]]` for the explicitly non-editing restrictions.

**Comment by Amorymeltzer** [comment]
Was gonna just merge it, but opened #1127 to make it easier to comment in case there's disagreement.
