### ISSUE TITLE
fluff: rollback confirmation on mobile devices

### ISSUE THREAD

**Issue by siddharthvp** [azatoth/twinkle#1130]
In addition to the TWPREF "Provide a confirmation message before reverting", a new preference should be created for mobile devices, so that we have:
- "Provide a confirmation message before reverting (on all devices)" -- retains the value of the original pref
- "Provide a confirmation message before reverting (on mobile devices only)"

For the second, the user-agent string can be checked for telling apart mobile devices: see https://en.wikipedia.org/wiki/MediaWiki:Gadget-confirmationRollback-mobile.js

**Comment by Amorymeltzer** [comment]
Seems exceedingly sensible!
