### ISSUE TITLE
Dialogs should have link to TWPREFS

### ISSUE THREAD

**Issue by siddharthvp** [azatoth/twinkle#1131]
To make WP:TWPREFS more discoverable, the Twinkle dialogs should have a morebits footerlink pointing to the relevant section (for that module) at TWPREFS.

**Comment by Amorymeltzer** [comment]
Is that even possible at the moment?  The content is added by config, so the sections are only added after the page is loaded.  Presumably it'd involve adding a hook into config to send folks to the section once the content has been loaded; that's probably a good idea regardless!

**Comment by Amorymeltzer** [comment]
See #1136, which should make this manageable.

**Comment by Amorymeltzer** [comment]
I've merged bug fixes #1135 and #1136, so this should now be trivial
