### ISSUE TITLE
Talkback: Redlink in NPOVN notifications

### ISSUE THREAD

**Issue by ToBeFree** [azatoth/twinkle#1165]
https://en.wikipedia.org/w/index.php?title=Wikipedia:Neutral_point_of_view/noticeboard&action=history

https://en.wikipedia.org/w/index.php?diff=984391784&diffmode=source

**Comment by Amorymeltzer** [comment]
Looks fixed to me!  😆

**Comment by ToBeFree** [comment]
Can't argue with that. 😜
