### ISSUE TITLE
Allow for tagging multiple history merges

### ISSUE THREAD

**Issue by atlight** [azatoth/twinkle#117]
From WT:TW:

> I found an article which was multiple times splitted and copy and pasted to another place. Why am I not allowed to tag the article with multiple history merges requests? mabdul 14:26, 3 May 2012 (UTC)
> 
> > Twinkle doesn't have very good history merge functionality at the moment. For some reason, history merge tagging is done using the CSD (speedy deletion) module, which doesn't make a lot of sense. I don't have much experience with history merges; how would you like Twinkle's functionality in this area to work? — This, that, and the other (talk) 09:38, 7 May 2012 (UTC)
> > 
> > > Tagging for non administrators is not bad actually. The problem with history merges is, that "easy merges" (clear copy and paste moves) are correctly tagged, but prevent the "tagger" to tag a page with multiple history merges. (which happens really seldom, but a few days ago I found an article which was moved two times by a user by copy and paste.)
> > > I would like to see (at least) a possibility to place multiple {{db-historymerge}} on a page.
> > > For more complex merges, I normally ask User:Anthony Appleyard at Wikipedia:Cut and paste move repair holding pen‎. Maybe ping him if more complex task should get added by TW at this page. (I have no opinion on that) mabdul 09:51, 7 May 2012 (UTC)

**Comment by Amorymeltzer** [comment]
I can't quite make out exactly what is being asked for here, but #536 (designed to fix a long-standing mislabeling and #293) will allow multiple taggings of (the template since renamed to) {{history merge}}, which I think is what this is asking for.

**Comment by Amorymeltzer** [comment]
Done (in a way) in #536
