### ISSUE TITLE
Duplicate section header for warnings

### ISSUE THREAD

**Issue by LuK3enwiki** [azatoth/twinkle#1205]
When adding subsequent warnings on user talk pages, it seems to duplicate the dated section header. For example: https://en.wikipedia.org/wiki/User_talk:75.135.106.30

It seems subsequent warnings and block templates seems to populate within the second section, see https://en.wikipedia.org/wiki/User_talk:97.90.7.200 for example.

**Comment by Amorymeltzer** [comment]
Thanks!  Fixed by #1207 (see also #1206)
