### ISSUE TITLE
TW doesn't detect headers placed by Cluebot NG

### ISSUE THREAD

**Issue by MagnusChase464** [azatoth/twinkle#1206]
See [here](https://en.wikipedia.org/wiki/User_talk:RichardSmith1).

Module: Warn

Note the two "November 2020" headers.

Console:

JQMIGRATE: Migrate is installed with logging active, version 3.1.0
load.php?lang=en&modules=jquery|jquery.ui&skin=vector&version=11ak3:155 This page is using the deprecated ResourceLoader module "jquery.ui".
Please use OOUI instead.
mw.loader.implement.css @ load.php?lang=en&modules=jquery|jquery.ui&skin=vector&version=11ak3:155
load.php?lang=en&modules=jquery|jquery.ui&skin=vector&version=11ak3:144 JQMIGRATE: jQuery.fn.delegate() is deprecated
migrateWarn @ load.php?lang=en&modules=jquery|jquery.ui&skin=vector&version=11ak3:144
DevTools failed to load SourceMap: Could not load content for chrome-extension://bhmmomiinigofkjcapegjjndpbikblnp/libs/bundle.min.js.map: HTTP error: status code 404, net::ERR_UNKNOWN_URL_SCHEME
DevTools failed to load SourceMap: Could not load content for chrome-extension://bhmmomiinigofkjcapegjjndpbikblnp/libs/lodash.min.js.map: HTTP error: status code 404, net::ERR_UNKNOWN_URL_SCHEME

**Comment by Amorymeltzer** [comment]
Thanks!  Fixed by #1207 (see also #1205)
