### ISSUE TITLE
CSD log should be more verbose

### ISSUE THREAD

**Issue by logological** [azatoth/twinkle#136]
It would be nice if the CSD log produced by Twinkle were more verbose.  In particular, I tag a lot of articles as CSD G5 (creation by banned user).  Twinkle prompts me for the name of the banned user, which it adds to the CSD template.  It would be nice if this information were also added to the log.  This would make reviewing the log very useful for identifying sockpuppets which recreate their own deleted articles.  Similarly, if Twinkle logged the URL prompted for CSD G12s, then reviewing the log for recreated articles would make it easier to find repeat copyvios.

I suppose that in general, whenever Twinkle prompts for further information when tagging an article for CSD, this information should be added to the log.

**Comment by Amorymeltzer** [comment]
@MusikAnimal @atlight Is this still desired?  Took a peek at the speedy module, theoretically this should be straightforward by abusing `params.templateParams`.  There are some complications (esp. for multiple noms, as  multiple templates use identical parameters) but figured I'd ask before taking a deeper look.  It seems a reasonable enough request, and folks might appreciate the info.

**Comment by MusikAnimal** [comment]
Seems helpful. Certainly not a bad idea. Go for it! :)

**Comment by Amorymeltzer** [comment]
@MusikAnimal I've got some code that should do this — was waiting until #436 is merged to do the final tests (though I don't think they conflict?) — but right now it inserts something like:

`additional information: [G6 rationale: house] [G7 rationale: g7] [G8 rationale: geight] [G12 url: test1.com] [G12 url2: test2.com] [G12 url3: test3.com];`

before the notified user message.  Any formatting you wanna change ?
