### ISSUE TITLE
Add deletion sorting

### ISSUE THREAD

**Issue by Ks0stm** [azatoth/twinkle#143]
https://en.wikipedia.org/wiki/User:John_Vandenberg/Deletion_sorting_tool required TW to work but has since started not working and, according to John Vandenberg, needs to be completely rewritten. Instead of having a standalone deletion sorting tool that requires TW it would be nice if deletion sorting was incorporated into TW.

**Comment by Amorymeltzer** [comment]
Agree with 2013-era comments: I think https://en.wikipedia.org/wiki/Wikipedia:WikiProject_Deletion_sorting#Scripts_and_tools is sufficient.  It's a pretty localized task, not something that needs Twinkle behind it.

**Comment by siddharthvp** [comment]
Unlike stub sorting, I think deletion sorting may have something to do with TW. Maybe we don't want a separate delesort module, but some limited delsort functionality could be built into the XFD module so that AFDs are sorted by the nominator as soon as they are created.
