### ISSUE TITLE
Merge FurMe with Twinkle

### ISSUE THREAD

**Issue by Amalthea** [azatoth/twinkle#15]
From TW-B-414:
;Rtrim issue on Google Chrom
Alright, I'm using both Firefox and Chrome for Ubuntu, and I'm running into an interesting issue on a script which relies on Twinkle. I don't know if it's your fault or AWeenieMan's fault, but Chrome is getting stuck on something that FF isn't. 

The code is the following (line 377), [[User:AWeenieMan/furme.js]]:
:<code>editSummary += 'adding ' + imageTags.replace('\n', ', ').rtrim(', ');</code>

Firefox will jump into line 1120, [[User:AzaToth/morebits.js]], into the following function:
:<code>String.prototype.rtrim = function stringPrototypeRtrim( chars )</code>

Google Chrome, however, errors out with this message: 

:<code>Uncaught TypeError: Object {{tl|Copy to Wikimedia Commons}},  has no method 'rtrim' {{right|1=/w/index.php?title=User:AWeenieMan/furme.js&action=raw&ctype=text/javascript:377}}
:furmeEditText {{right|1=/w/index.php?title=User:AWeenieMan/furme.js&action=raw&ctype=text/javascript:377}}
:furme {{right|1=/w/index.php?title=User:AWeenieMan/furme.js&action=raw&ctype=text/javascript:132}}
:addOnloadHook {{right|1=bits.wikimedia.org/skins-1.5/common/wikibits.js?283-5:52}}
:(anonymous function) {{right|1=/w/index.php?title=User:AWeenieMan/furme.js&action=raw&ctype=text/javascript:52}}</code>

[[User:Magog the Ogre|Magog the Ogre]]([[User talk:Magog the Ogre|talk]]) 22:49, 29 October 2010 (UTC)

PS. I've tried it on Windows and it fails there too. It can be reproduced by installing FURME, going to [[:File:Harry Bemis.jpg]] and clicking tag -> and choosing any of the options below (i.e., the ones not in the dropdown), and clicking submit. [[User:Magog the Ogre|Magog the Ogre]]([[User talk:Magog the Ogre|talk]]) 23:01, 29 October 2010 (UTC)

**Comment by Amorymeltzer** [comment]
Closing as this has stalled.  Image tagging has been happy and healthy in Twinkle for a while now (see ab9f7898) and we support Di options, so I'm not certain there's much else we'd really want anyway.

**Comment by siddharthvp** [comment]
@Amorymeltzer Has all of FurMe been merged into TW? The note at WP:FurMe says "image maintenance tagging has been partially merged". If so, it'd be better to leave this open to allow an interested editor to merge the rest.

**Comment by Amorymeltzer** [comment]
That's precisely my point.  The work has been entirely abandoned for the better part of a decade — the branch was last touched in 2011 — and there's no indication anyone still *wants* the rest of it.  The main thing missing are the extensive fair use stuff — `Non-free currency-EU coin national` and all that — so if there's a clamoring for it, sure, but the rest of it isn't relevant and it's not something that, as far as I can see, anyone wants to actively pursue.
