### ISSUE TITLE
Fetch tokens from mw.user.tokens instead of via the API

### ISSUE THREAD

**Issue by legoktm** [azatoth/twinkle#153]
Right now when using deli-batch for a category (which is wonderful btw!), it fetches a delete token for each file and then proceeds to delete them.
Deletion tokens are not different for each page, so it would be more efficient to just fetch it once and pass it onto all the requests.

**Comment by atlight** [comment]
Batch modules now use `mw.user.tokens`, so deleting 6 pages now takes 6 API requests. For various reasons stated above, tokens are still fetched from the API for other types of requests.
