### ISSUE TITLE
XfD Preview

### ISSUE THREAD

**Issue by WP-MrX** [azatoth/twinkle#168]
I would like to propose a preview link for previewing XfD nominations, similar to the preview link available when posting a user talk page warning/notification with Twinkle. 

It's frequently necessary to include wikilinks to articles, previous discussions, and policy and guideline pages when submitting an XfD. Since it is so easy to make a typo, or to choose the wrong policy shortcut, it would be very handy to have the ability to preview a nomination before creating it.

**Comment by atlight** [comment]
I'm going to "taking the plunge" and putting this forward as a Google Code-In task. Wikimedia is [participating](https://www.mediawiki.org/wiki/Google_Code-in_2015) in this coding event for 13- to 17-year-olds, so I thought I would throw our hat in the ring and use this task to see if GCI can benefit us.

### Additional information for GCI students

[Twinkle](https://en.wikipedia.org/wiki/WP:TW) is a popular JavaScript gadget used by thousands of Wikipedians to accelerate common maintenance tasks. The code is [hosted on GitHub](https://github.com/azatoth/twinkle).

Twinkle allows users to make posts to various wiki pages, such as starting a deletion discussion, or welcoming a new user on their user talk page. Users should be able to preview the post or message before Twinkle places it on the wiki.

Currently, the "welcome" and "warn" modules provide preview functionality using `Morebits.wiki.preview` class. Your task is to add preview functionality to the "xfd" (deletion discussions) module, based on the model of the "warn" module.

Separate code will be required for each of the eight discussion venues supported by Twinkle. To complete this task, you should add preview functionality for at least three venues.

You should test your code in Internet Explorer (running in IE9 emulation mode) and another browser of your choice. (If you do not have access to a computer running Windows Vista or later, let the mentor know and he will test in IE on your behalf.)
