### ISSUE TITLE
Auto-editprotected when XfD-ing protected pages

### ISSUE THREAD

**Issue by atlight** [azatoth/twinkle#176]
> When we use Twinkle to TfD or TfM a protected template, it would be handy if an {{Editprotected}} section could be automatically added to the template's talk page.
> 
> For examples, see Template talk:Infobox member of the Knesset#TfD and Template talk:Infobox royalty#Merge propsal. Andy Mabbett (Pigsonthewing); Talk to Andy; Andy's edits 12:53, 13 July 2013 (UTC)

The XfD module needs some thinking - perhaps unify some of the code paths if at all possible?

**Comment by RhinosF1** [comment]
Is this going ahead?

**Comment by Amorymeltzer** [comment]
@RhinosF1 Yes.  I've got some work on it, but I've been focusing on some other fixes to XfD, in particular #515, #521, and #527.  I think it might need some hacking to `morebits` which means it'll take me a bit longer, but it's on the todolist regardless.

**Comment by RhinosF1** [comment]
Thanks

**Comment by siddharthvp** [comment]
@Amorymeltzer what's the status on this?

>  I think it might need some hacking to morebits 

Indeed. It will be necessary for the failure callback to know what error occurred, and take action only if it was `protectedpage`. This will need #679 to go ahead first, as that changes the argument passed to the failure callback from `pageobj` to `apiobj` which does have the error code.

**Comment by Amorymeltzer** [comment]
@siddharthvp Short answer: focused on other things.  I'd blame you and all your wonderful contributions that I worked on around this time (#485 and #581 come to mind), but this summer and the months after I was unexpectedly occupied; you may have noticed that most of my recent warn-related PRs were mostly written in June, and I was barely active.

If you want to work on it, by all means go ahead!  I'm away for a couple weeks ahead of the end-of-year holidays, but I want to get most of the current slate of PRs from you and me (including #679) merged and pushed in January.  This is on my "next up" list after that.

**Comment by Amorymeltzer** [comment]
FWIW, `pageobj` has the status element available, which can be used to get the error text and naively intuit the error itself.
