### ISSUE TITLE
Multiple CSD criteria on admin CSD module

### ISSUE THREAD

**Issue by Callanecc** [azatoth/twinkle#197]
Is it possible for the admin's CSD module to be expanded to allow for multiple criteria to be selected (the same way for non-admins tagging pages)?
Thanks,
Callanecc

**Comment by MusikAnimal** [comment]
What a coincidence. Just now going through all the issues, and seeing that even I had commented on this over a year ago, before I got involved with Twinkle development. Well, guess what, this is coming! Very soon! Would you be interested in helping test it, @Callanecc?

**Comment by Callanecc** [comment]
Yeah, no worries. Déjà vu?

**Comment by Amorymeltzer** [comment]
Done in 26d974ce

**Comment by MusikAnimal** [comment]
Indeed!
