### ISSUE TITLE
Include expiry parameter when applying protection tags as a non-admin

### ISSUE THREAD

**Issue by atlight** [azatoth/twinkle#202]
From WT:TW:

> With the admin protection interface, would it be possible for Twinkle to automatically include the expiry parameter when the interface is being used to protect the page? Thanks, Callanecc (talk • contribs • logs) 08:00, 3 December 2013 (UTC)
> 
> > @Callanecc: Could you elaborate a bit here? I'm not quite sure what you're referring to. Do you mean the |expiry= parameter on the protection tags? — This, that and the other (talk) 05:04, 6 December 2013 (UTC)
> > 
> > > Sorry, yep that's what I was referring to. Callanecc (talk • contribs • logs) 06:12, 6 December 2013 (UTC)

I suppose it's a matter of looking at `wgRestrictionEdit` in mw.config, if applying a protection tag to an already-protected page, or else looking at the new protection being applied by Twinkle.

**Comment by Amorymeltzer** [comment]
No longer needed (see #363); removed in #442
