### ISSUE TITLE
Changes to default protection durations

### ISSUE THREAD

**Issue by Callanecc** [azatoth/twinkle#217]
SEMI-PROTECTION PRESETS
At the moment (when selecting any semi-protection as a preset) the default move protection is an indefinite full protection. Wikipedia's default is to duplicate what is currently selected as the edit protection. Given that would it be possible for the deafultWould it be possible for the Twinkle protection module to do the same?

FULL-PROTECTION PRESETS
The same could be done for full protection presets, for example rather than the default move protection length being indefinite can it be the same as the edit protection default (which is currently 2 days)?

Thanks,
Callanecc

**Comment by atlight** [comment]
@MusikAnimal Is this still an issue?

**Comment by Callanecc** [comment]
Whether this is an issue to be fixed is obviously up to you. But Twinkle still has the same behaviour as when I initiated the request.

**Comment by MusikAnimal** [comment]
It is true Twinkle differs from the normal form in the default duration of move protection, but I have to ask is this truly desirable? When I protect against moves, I'm usually inclined to believe it's not likely to change moving forward. Obviously not always the case, but the prime example simply being vandalism. E.g. `Google` being changed to `Google on wheels!`. Well that's it, we've reason to protect, so indef it is. Or `U.S. Open` being changed to `US Open`. That could also go to `United States Open` etc, let's put a halt to the ambiguity and force discussion once we've seen it's an issue. Page moves should be infrequent, is my thought.

So for Twinkle I just think we should default to whatever is most convenient or the most common scenario. If we feel that's a temporary duration we can make it happen, no problem. What do you think?

**Comment by Callanecc** [comment]
True, however if you're protecting due to an edit war why would you want indefinite move protection?

**Comment by MusikAnimal** [comment]
Ah, sorry, I should have read what you say more carefully =P With full protection against edit warring it does default to indef move protection, when page moves may have nothing to do with it. In that case yes it's quite sensible to have the durations be the same. Same if you semi-protect then check the move protection, it should only semi-protect the move for the same duration. Correct? Meanwhile, selecting move protection by itself will default to indefinite sysop. I guess that equates to default MediaWiki behaviour! We can make this happen :)

**Comment by Callanecc** [comment]
Exactly my thoughts! :)

**Comment by MusikAnimal** [comment]
Also I can try to make the durations sync as they do with MW, where if you change the protection level/duration of the page, the move protection settings change with it, but not the other way around

**Comment by MusikAnimal** [comment]
Eh, or I guess that shouldn't happen once the move protection option has been checked. Syncing it like that when both are checked might present an odd user experience

**Comment by MusikAnimal** [comment]
All set with https://github.com/azatoth/twinkle/pull/301
