### ISSUE TITLE
Template:Uw-sanctions is deprecated; Template:Alert

### ISSUE THREAD

**Issue by wikiagk** [azatoth/twinkle#219]
Hello. Due to changes by ArbCom to the discretionary sanctions system, Template:Uw-sanctions is deprecated. Could you please remove it from the Twinkle system? Template:Alert, a neutral informational notice (not a user warning!), has also been made available for arbitration areas of conflict. Could this template be added to the system?

Anthony (User:AGK)

**Comment by Amorymeltzer** [comment]
Closing as `uw-sanctions` wasn't in Twinkle, and I don't think we want to add `Ds/alert` — it's a complex process for even experienced users, and as Twinkle is open to any autoconfirmed user seems ripe for misuse.  Moreover, there are *a lot* of options, so it might be tricky to fit in to the warning menu.  There's a [user-developed pluging](https://en.wikipedia.org/wiki/User:Bellezzasolo/Scripts/arb) that actually does this.  The edit filter stuff is in #182.

**Comment by Amorymeltzer** [comment]
@wikiagk: Do let me know if you or anyone else at AC disagrees!
