### ISSUE TITLE
Twinkle added my maintenance tag in the wrong place

### ISSUE THREAD

**Issue by gparyani** [azatoth/twinkle#221]
I wanted to add a maintenance tag to [Poway High School](http://en.wikipedia.org/wiki/Poway_High_School). However, since the first section contained a multiple issues maintenance tag, it added the tag to the first section's multiple issues tag instead of to the top of the article. Example revision: https://en.wikipedia.org/w/index.php?title=Poway_High_School&diff=612281820&oldid=612281653

**Comment by QEDK** [comment]
@gparyani You are actually bypassing your automated edit summary derived SAEC check by removing TW from your edit summary. Just saying.

**Comment by gparyani** [comment]
@QEDK What do you mean?

**Comment by QEDK** [comment]
@gparyani Your edit doesn't contain the generic (TW) part.

**Comment by gparyani** [comment]
Any progress on this bug?

**Comment by atlight** [comment]
I'll try to have a look at it. Thankfully I imagine it's quite rare; I have never seen {{multiple issues}} applied to sections in the articles I read and edit.
