### ISSUE TITLE
Allow us to mark articles as stubs using Twinkle

### ISSUE THREAD

**Issue by gparyani** [azatoth/twinkle#222]
Twinkle should have the ability to mark articles as stubs. Right now, I have to look in the list of stub templates and then pick out the right one. Give us this ability so that we can do it inline!

**Comment by Amorymeltzer** [comment]
Closing as stalled.

Like deletion sorting, this is a relatively niche interest and there are already a few stub-tagging options on-wiki that seem to work fine.
