### ISSUE TITLE
Get rid of XPath!!

### ISSUE THREAD

**Issue by atlight** [azatoth/twinkle#226]
There's still some XPath in batchdelete and batchundelete. Don't know how that slipped through the cracks. IE has never properly supported XPath, so it needs to be killed and replaced with jQuery.

**Comment by atlight** [comment]
The last vestiges of XPath were finally removed in 5b4c9e61bca2eda58c43b5ba41a237c04cc7e6aa.

**Comment by hartman** [comment]
:fireworks:
