### ISSUE TITLE
Change in AFCHD/u

### ISSUE THREAD

**Issue by Mdann52** [azatoth/twinkle#235]
Hi all,

[template:AFCHD/u](https://en.wikipedia.org/wiki/AFCHD/u) has recently changed, removing the parimiter linking to the draft in question, instead standardising with similar templates and only linking to section. Therefore, it would be appreciated if Twinkle could change to reflect this. Therefore, instead of a "link to draft" parimiter, it should just offer a "link to section" option.

**Comment by atlight** [comment]
What was the outcome here? I assume the issue with the template was gixed?

**Comment by Technical-13** [comment]
https://en.wikipedia.org/w/index.php?title=Template%3AAFCHD%2Fu&diff=616089530&oldid=615944385 seems to indicate that I did in fact make changes to the template, and since I've heard nothing else about it, I must assume that it is in fact done and this request can be closed.

**Comment by Amorymeltzer** [comment]
Per https://en.wikipedia.org/w/index.php?title=Template:AFCHD/u&diff=877887542&oldid=613814510 it seems nothing but language has changed.
