### ISSUE TITLE
Request: put maintenance tags below deletion notices

### ISSUE THREAD

**Issue by Breza** [azatoth/twinkle#237]
Would it be possible for Twinkle to put new maintenance tags below CSD/PROD/AFD tags?  It would prevent me from having to fix edits like this: https://en.wikipedia.org/w/index.php?title=Bell_Integrator&diff=616390399&oldid=616389887

**Comment by Amorymeltzer** [comment]
This is the tag module's [massive regex](https://github.com/azatoth/twinkle/blob/b8d57ba15a219d1769f7d493509b6dc70730c252/modules/friendlytag.js#L1167).

**Comment by Amorymeltzer** [comment]
#541 should do CSD and PROD, but as I said there, AfD is trickier.  It leads not with a template but with a comment:

`<!-- Please do not remove or change this AfD message until the discussion has been closed. -->`

That poses all sorts of annoyances, since that comment is followed by a template and then two more comments, one of which has template code inside of it.  It's fairly predictable, at least, but annoying.

**Comment by Amorymeltzer** [comment]
So, for AfD, something like the below could work:

```javascript
<!-- Please do not remove or change this AfD.*\n\{\{Article for deletion\/dated.*\n<!-- Once discussion.*\n<!-- End of AfD message.*|
```

That's a fairly unique sequence and could probably be shortened to something like the below without losing any specificity, fidelity, or clarity:
```javascript
<!--.*AfD.*\n\{\{Article for deletion\/dated.*\n<!--.*\n<!--.*AfD.*|
```

That'd make the final line look something like the untested:
```javascript
pageText = pageText.replace(/^\s*(?:((?:\s*<!--.*AfD.*\n\{\{Article for deletion\/dated.*\n<!--.*\n<!--.*AfD.*|\{\{\s*(?:db|delete|db-.*?|speedy deletion-.*?|(?:proposed deletion|prod blp)\/dated|about|correct title|dablink|distinguish|for|other\s?(?:hurricaneuses|people|persons|places|uses(?:of)?)|redirect(?:-acronym)?|see\s?(?:also|wiktionary)|selfref|the)\d*\s*(\|(?:\{\{[^{}]*\}\}|[^{}])*)?\}\})+(?:\s*\n)?)\s*)?/i,
```

This is why /x was invented 😡

**Comment by siddharthvp** [comment]
> This is why /x was invented 😡

If the issue is readability, how about breaking down the regex into something like:
```javascript
pageText = pageText.replace(
	new RegExp(
		// leading spaces
		'^\s*' +
		// begin capturing group
		'(?:(' +
		'(?:\s*' +
		// begin template
		'\{\{\s*(?:' +
			// speedy deletion templates
			'db|delete|db-.*?|speedy deletion-.*?|' + 
			// proposed deletion templates
			'(?:proposed deletion|prod blp)\/dated' +
			// hatnote templates
			'about|correct title|dablink|distinguish|for|other\s?(?:hurricaneuses|people|persons|places|uses(?:of)?)|redirect(?:-acronym)?|see\s?(?:also|wiktionary)|selfref|the' +
			//  dunno what this \d* is here for  :(
			')\d*\s*' +
			// parameters
			'(\|(?:\{\{[^{}]*\}\}|[^{}])*)?' +
		// end template
		'\}\})+' +
		// end capturing group
		'(?:\s*\n)?)' +
		// trailing spaces
		'\s*)?',

	'i'),

	"$1" + tagText
);
```

**Comment by Amorymeltzer** [comment]
@siddharthvp Indeed!  I mostly held off to avoid regex hell, but I dove in a few days ago and am almost out.  I'll have something (with some other fixes) soon(ish).
