### ISSUE TITLE
Loses part of AN3 comments when these contain a syntax error

### ISSUE THREAD

**Issue by Chealer** [azatoth/twinkle#240]
I filed an AN3 report using Twinkle which was supposed to result in something like the section changed in http://en.wikipedia.org/w/index.php?title=Wikipedia:Administrators%27_noticeboard/Edit_warring&diff=621310927&oldid=621310299

Instead of that, it was submitted like the previous version shows, truncated in the middle of an external link. I confused the syntaxes for external links and internal links and used a pipe instead of a space to separe the URL and the label (I repeated that error in the edit supposed to fix the issue). I believe that error is what broke Twinkle.

This happened silently, I did not notice any error. I simply realized that a large part of my comments were missing, and congratulated myself for having copied the field's contents before submitting.

Note that I had to manually complete other fields after filing the report. Having the possibility to preview would have avoided and probably would have let me spot my syntax errors.

**Comment by Amorymeltzer** [comment]
Can't replicate
