### ISSUE TITLE
Request: Could twinkle please include WP:NFRINGE as a subcategory of the {{notability}} template?

### ISSUE THREAD

**Issue by salimfadhley** [azatoth/twinkle#241]
I do a lot of patrolling for [WP:FTN](https://en.wikipedia.org/wiki/Wikipedia:Fringe_theories/Noticeboard) (the Fringe Theory Noticeboard), generally I'd like to be able to autotag pages which contain fringe-theory promoting content but do not appear to meet the notability standards for fringe-theory content, as stated here:

https://en.wikipedia.org/wiki/Wikipedia:NFRINGE#Notability

**Comment by atlight** [comment]
[Template:Fringe theories](https://en.wikipedia.org/wiki/Template:Fringe_theories) exists. However, I note the comment on the template's documentation page:
>Drive-by tagging is strongly discouraged. The editor who adds the tag should first discuss concerns on the talk page, pointing to specific issues that are actionable within the content policies, and should add this tag only as a last resort. In the absence of such a discussion, or where it remains unclear what the NPOV violation is, the tag may be removed by any editor.

As such I don't think it would be appropriate to add this tag to Twinkle. If you find yourself using it frequently, you can add it to your custom tags at [TWPREFS](https://en.wikipedia.org/wiki/Wikipedia:Twinkle/Preferences#twinkle-config-section-8).
