### ISSUE TITLE
Use {{db-spamuser-sandbox}} instead of {{db-spamuser}} on user sandboxes

### ISSUE THREAD

**Issue by gparyani** [azatoth/twinkle#244]
When nominating a user page under speedy deletion criterion "G11: Promotional user page under a promotional user name", it puts a template {{db-spamuser}} onto the page. However, for the user _sandbox_ specifically, it should instead use the template {{db-spamuser-sandbox}} which is a special version of {{db-spamuser}} designated specifically for user sandboxes. The option should remain the same, but the actual template used to tag the "sandbox" subpage of a user page should use the special user sandbox template instead. For the main user page and user subpages that are not "sandbox", it should continue to use {{db-spamuser}}.

**Comment by gparyani** [comment]
@atlight Maybe there are two different templates because there are two different user warnings for both templates?

**Comment by atlight** [comment]
That's not a very good reason to have separate templates. The user talk template should then detect whether it is being used in relation to a user sandbox, shouldn't it?

**Comment by gparyani** [comment]
@atlight You may want to voice your concern at the Db-meta talk page, then...

**Comment by atlight** [comment]
The solution here is to fix the templates.
