### ISSUE TITLE
Add reason support for Template:Di-replaceable fair use

### ISSUE THREAD

**Issue by ListenerJubatus** [azatoth/twinkle#247]
{{:Di-replaceable fair use}} allows users to specify a reason for why the image is replaceable fair use, but Twinkle does not allow use of this parameter. Can it please be implemented?

**Comment by atlight** [comment]
It does, but to allow for full access to the reason parameter (`1=`) for those not using Twinkle, it needs to be made available in `{{subst:rfu}}`.

**Comment by atlight** [comment]
Fixed here in GitHub; it will be fixed on-wiki when an admin next comes around.
