### ISSUE TITLE
Add option to give an ISO 639-1 code for "R from alternative language" redirect tags

### ISSUE THREAD

**Issue by AmaryllisGardener** [azatoth/twinkle#250]
Title pretty much says it all, can someone add the option to give an ISO 639-1 (i.e. "pt" for Portuguese", "ja" for Japanese") code for "R from alternative language" redirect tags?

**Comment by QEDK** [comment]
Okay, upon checking, I found that there's a to and from parameter. Are both of these necessary or optional?

**Comment by AmaryllisGardener** [comment]
As far as I know, "R to alternative language" doesn't exist.

**Comment by QEDK** [comment]
No, no, no, no, no. I was talking about the `|to=   ` and `|from=   ` parameters.

**Comment by AmaryllisGardener** [comment]
Oh, I see. neither "to" or "from" have to be listed, but it's better to list them, especially "from".

**Comment by QEDK** [comment]
@atlight , assign this to yourself. My exam starts day after tomorrow. Meanwhile, if you can, ask PamD to gain consensus for adding that bouncy ball to the template.
