### ISSUE TITLE
In submenu names, please use triangles such as "‣" instead of bold and ellipses

### ISSUE THREAD

**Issue by jasonspiro** [azatoth/twinkle#258]
Twinkle's "User" menu includes two options which actually pop out submenus.  These are:

    User logs...
    Analysis...

It would be good if you could please change these option names to:

    User logs     ‣
    Analysis      ‣

and if you could please unbold them.

It is good that you now use UI cues to indicate the presence of a submenu.  But the use of bold and ellipses contradicts longstanding UI convention.  The longstanding convention is to use [triangles](http://www.google.com/search?tbm=isch&q=file+menu).  Ellipses are normally used in UI solely to indicate that an option calls up a dialog box -- never for any other purpose.  And bolding a menu item name is simply confusing.

P.S.  Thank you for continuing to improve Twinkle!  It only keeps getting better and better.

**Comment by atlight** [comment]
This is not Twinkle, this is some other gadget :)
