### ISSUE TITLE
Make the "TW" button more touch-friendly

### ISSUE THREAD

**Issue by gparyani** [azatoth/twinkle#261]
When I'm using the Modern app version of Internet Explorer and a touchscreen on Windows 8.1, there are certain problems when tapping the button. When I tap the button using the touchscreen, nothing happens. At all. The module only expands when I use a mouse and put my cursor on it. In addition, when my mouse cursor is already over it, if I tap away from it in order to collapse it, it still remains expanded. The only workaround I've discovered to date is to switch to the MonoBook skin, which separates out the buttons instead of collapsing them. Is it possible that you can detect touchscreens (by checking for the string "Touch" in the user agent string) and supply some extra modifications to touchscreen users so that the button works when tapped (in the Vector skin)?

**Comment by gparyani** [comment]
Okay, I've found the trick, which is to tap and hold until the menu appears (I don't know why). This should be made more documented.

**Comment by atlight** [comment]
Yes, it should be made more documented by Internet Explorer, not really by us. Having said that, if you'd like to update the Twinkle documentation at [[WP:TW/DOC]] with your findings, that could be helpful.
