### ISSUE TITLE
Uw-attack should not have parameter 1 for the page

### ISSUE THREAD

**Issue by Callanecc** [azatoth/twinkle#262]
There was consensus some time ago that the two attack page warning templates (Db-attack-notice and Uw-attack) should not include a link to the page - https://en.wikipedia.org/wiki/Wikipedia_talk:Template_messages/User_talk_namespace/Archive_12#Template:Db-attack-notice_needs_modification.

I thought the Twinkle devs were contacted at the time however it must have been overlooked. Could this please be fixed as soon as possible. See also recent revisions https://en.wikipedia.org/w/index.php?title=Template:Uw-attack&action=history

Thank you, Callanecc

**Comment by atlight** [comment]
Your recent edits will stop the name of the attack page from appearing in the page content, and Twinkle already omits the page name from the edit summary when applying {{uw-attack}}. No modification is required to Twinkle.

Similarly, the db-attack-notice template does not include a page name parameter within its wikitext, and Twinkle again omits the page name from the edit summary for G10 deletion notifications.

Do you have evidence that either of these mechanisms is failing?

**Comment by Callanecc** [comment]
Hi This, that and the other, I was thinking more graying out the 'linked
article' box so it can't be entered and it's obvious that it can't?

Callanecc

**Comment by gparyani** [comment]
This issue is now obsolete, as db-attack-notice now actually uses the parameter.

**Comment by atlight** [comment]
So it does.
