### ISSUE TITLE
More IP user welcome templates

### ISSUE THREAD

**Issue by TheBrianiac** [azatoth/twinkle#263]
I would love for some IP-user equivalents of many of the regular user welcomes. It's a bit awkward to use one that says "Hey, 123.456.789, welcome to Wikipedia!" But, at the same time, I need issue-appropriate messages. Thanks!

**Comment by atlight** [comment]
If you create the templates we'll consider adding them. On the other hand it also might be nice to see whether the problem user templates can be made not to display IP addresses next to the word "hello"; as you say, it's silly.

**Comment by atlight** [comment]
I think this should be fixed now. For problems for which there is no anon-specific welcome template, you can now use the general purpose welcome on the "Standard welcomes" tab, and the user will no longer be greeted with "Hello 192.168.1.1" or something similar.

Let me know if I have missed something out. Thanks!
