### ISSUE TITLE
rollback vandal should indicate that was used

### ISSUE THREAD

**Issue by Terebi42** [azatoth/twinkle#264]
When using the rollback-vandal link, no indication is made that the rollback was made due to perceived vandalism. Such would be helpful in the edit summary (since none is prompted for)

**Comment by martijnhoekstra** [comment]
IMO using rollback, *unless* there is an explaining note, always implies vandalism, and as such, this isn't needed

**Comment by gparyani** [comment]
It used to say "identified as vandalism" in the edit summary a while ago; why was this removed? (Example: http://en.wikipedia.org/w/index.php?diff=165910897)

**Comment by atlight** [comment]
There was a significant discussion at WT:TW some time ago. (I'm not in a position to find you the link right now unfortunately, but I suggest you check it out in the archives.)

If you would like it changed, start a discussion at WT:TW. If an agreement is reached we can then reopen this issue.

**Comment by Terebi42** [comment]
I have opened a discussing at WT:TW
https://en.wikipedia.org/wiki/Wikipedia_talk:Twinkle#mark_rollback_vandalism_as_vandalism_in_edit_summary
