### ISSUE TITLE
Use tag instead of edit summary suffix to identify Twinkle edits

### ISSUE THREAD

**Issue by jimmyxu** [azatoth/twinkle#265]
Now that we can define custom tags in MediaWiki and slap them on when editing, is it better to use that instead of the (TW) suffix? It's probably better for stats purposes, but I should say I have no idea how much people customize the suffix, or how they need the customizability.

Currently it [looks like this](https://zh.wikipedia.org/w/index.php?title=Special:Recentchanges&tagfilter=Twinkle&uselang=en) on zhwiki, and only [one line of code](https://github.com/jimmyxu/twinkle/commit/20fbe1518043e4aaa7fd6ef4fa0f2f0dc3929ad3) needs to be added.

**Comment by Technical-13** [comment]
You'd have to establish a consensus to create a tag -- see http://en.wikipedia.org/wiki/MediaWiki_talk:Tag-OneClickArchiver for the RfC on this.

**Comment by jimmyxu** [comment]
Well I had emptied the `summaryAd` on zhwiki just now and will let it run for some days. If it looks good then maybe I (or someone interested who are better in enwiki :) would post something on WT:TW.

**Comment by gparyani** [comment]
I'd rather prefer that my edits not be identified as having been done using Twinkle. It's nice that you can remove it from the signature.

Also, I don't think that this will attain consensus as changing TW mean that HG, CSDH, AWB, AFCH, and a bunch of others also need to be changed as well.

**Comment by Technical-13** [comment]
They already are, it's intergrated and part of the edit summary.  On top of that, there is a tool on labs that will find all of your edits using TW and list them. Moving that to a separate tag doesn’t  change that any.  I suppose TW could offer an option to get rid of the tag.

As far as your second point goes, it wouldn't mean 'all' of the other tools would be changed. Each tool maintainer crew will have to make their own decision.

**Comment by gparyani** [comment]
@Technical-13 Yes, but only *by default* is (TW) added to the edit summary. One can go to Wikipedia:Twinkle/Preferences and have that changed or removed if one wants. For example, look at most of the edits on my account; you'll see that they're obviously made using Twinkle, but they don't show the (TW) in the edit summary because I removed it.

I'd rather not explicitly show that my edits are made using Twinkle, and adding a tag would cause all edits made using it to be shown as such against the user's will. If this is implemented, consider making the addition of the tag optional, not mandatory.

**Comment by Technical-13** [comment]
Nothing changes by moving that TW from the edit summary ro a tag, and I expect you'd still be able to have it omitted.

**Comment by gparyani** [comment]
@Technical-13 Yes, maybe in the final configuration, but in the one that the OP supplied, this isn't possible.

**Comment by jimmyxu** [comment]
@gparyani This kind of stuff is the reason why I didn't submit this as a pull request :)

On a side note, it looks good on zhwiki as far as I can see.
