### ISSUE TITLE
Warn before allowing PROD if the talk page is a member of Category:Past proposed deletion candidates

### ISSUE THREAD

**Issue by gparyani** [azatoth/twinkle#266]
With the exception of BLP PROD, if an article has been nominated for proposed deletion before, and the PROD has been contested by someone else (either by removing the PROD tag or by requesting undeletion of a deleted PRODed article at [[Wikipedia:Requests for undeletion]]), the article cannot be proposed for deletion again and must instead be taken to Articles for Deletion. In addition, anyone who contests a PROD is supposed to add the template [[Template:Old prod full]] to the article's talk page, which will make it a member of [[:Category:Past proposed deletion candidates]].

I propose that Twinkle should check to see if the article's talk page is a member of this category when a user chooses to propose an article for deletion via PROD, and if it is, it should warn the user with a message that says that the article has already been nominated for PROD in the past and suggest that the user use AfD instead.

Note that the above only applies to regular PROD, not to sticky BLP PROD (which can be done at any time if a BLP becomes unsourced, and must remain as long as it is unsourced).

**Comment by gparyani** [comment]
Been over a month; anyone looking?

**Comment by atlight** [comment]
Yes, I'm looking, but it's hardly a priority.

**Comment by gparyani** [comment]
Glad to see that this is finally being done... @Amorymeltzer out of curiosity, what finally prompted the implementation of this?

**Comment by Amorymeltzer** [comment]
@gparyani The work for #435/#567 was made possible by @siddharthvp, and this was the logical parallel.  Also, I dunno, I found it and agreed with it and it seemed doable!
