### ISSUE TITLE
RPP requests are supposed to be at the bottom, not the top

### ISSUE THREAD

**Issue by gparyani** [azatoth/twinkle#269]
When I nominate a page for protection at RPP, Twinkle puts the request in at the top. However, there are very clear instructions that state, "Place requests for new or upgrading pending changes, semi-protection, full protection, move protection, create protection, template editor protection, or upload protection at the **BOTTOM** of this section." Twinkle should therefore list them at the bottom, not the top.

By the way, this was a very recent policy change; it **used** to be that they would be placed at the top.

**Comment by atlight** [comment]
This should have been fixed in c91ed798048ee104eb2cbde244bff30175f51db7 but it hasn't been synced yet. @Amalthea do you think you could do this, and just give it a quick test (nominate some page at RPP) to make sure it posts at the bottom?

**Comment by Amalthea** [comment]
sync done, testing it in dev mode worked, will try to remember to test it in a few minutes with the live gadget ...
