### ISSUE TITLE
Check behaviour of "Cancel" button in prompts on Safari

### ISSUE THREAD

**Issue by atlight** [azatoth/twinkle#274]
Something on WT:TW ([now in Archive 36](https://en.wikipedia.org/wiki/Wikipedia_talk:Twinkle/Archive_36#Bug:_When_you_press_cancel_on_the_%22Restore_this_revision%22_in_Safari)) about the "cancel" button on the prompt dialog not actually cancelling the action in Safari.

> When you press cancel on the "Restore this revision" in Safari on Mac OS X, It will proceed to revert WITHOUT an edit summary or my consent instead of just cancelling the revert as expected.

**Comment by atlight** [comment]
Not really a bug in Twinkle, but it will do.

The solution to this, and the immersive browser issue, may be to write our own prompt code. The big issue is one of (a)synchrony, but it will also be good to get rid of modal prompts and use subgroups in more places.

**Comment by Amorymeltzer** [comment]
I can't replicate this (Safari 11.1.2 (11605.3.8.1), macOS X.11.6).

**Comment by atlight** [comment]
Happy to close this, then. Presumably Safari has lifted its game since 2015.
