### ISSUE TITLE
AdBlock extension blocks Twinkle

### ISSUE THREAD

**Issue by cymrulass** [azatoth/twinkle#275]
Hey, just so you know, the AdBlock Plus browser extension seems to think Twinkle is an ad, at least on Chrome. I was wondering why the TW panel wasn't popping up despite me having it enabled in my preferences, and I tried disabling a few addons. As soon as I disabled AdBlock and refreshed, Twinkle reappeared. You might want to have a chat with them about whitelisting you. The forum link for bug reports for the Chrome version is https://adblockplus.org/forum/viewforum.php?f=10

**Comment by gparyani** [comment]
Seems like something to do with a filter list, not with Adblock Plus itself. Try disabling each filter list you have enabled one by one, and once you find the faulty one, report the problem to the writer of that list.

Alternatively, try switching from Adblock Plus to [AdBlock](http://getadblock.com), and see if you have the same problem with it.

Speaking of which, I have EasyList enabled as a Tracking Protection List in Internet Explorer 11, and Twinkle isn't blocked.

**Comment by atlight** [comment]
Doesn't seem like an issue with Twinkle.

It's great to see you back though, cymru.lass!
