### ISSUE TITLE
Ignore CBNG edits when reverting vandalism

### ISSUE THREAD

**Issue by Gaelan** [azatoth/twinkle#277]
Imagine this page history:
```
(cur | prev) 23:52, 2015 February 18‎ EvilVandal (talk | contribs)‎
(cur | prev) 23:51, 2015 February 18‎ EvilVandal (talk | contribs)‎
(cur | prev) 23:49, 2015 February 18‎ EvilVandal (talk | contribs)‎
(cur | prev) 23:48, 2015 February 18‎ Cluebot NG (talk | contribs)‎ (Revert vandalism.)
(cur | prev) 23:47, 2015 February 18‎ EvilVandal (talk | contribs)‎
(cur | prev) 23:46, 2015 February 18‎ EvilVandal (talk | contribs)‎
```
When clicking "revert vandalism" on the current edit, Twinkle will only revert up to the CBNG revert. Instead, Twinkle should also revert edits by Cluebot, as long as they are sandwiched by the user to be reverted.

\~~~~ :)

**Comment by gparyani** [comment]
Can you give an example? If CBNG does a rollback instead of a simple revert, this issue isn't really necessary to resolve. (I saw no documentation on its user page or its FAQ page about it.)

**Comment by MusikAnimal** [comment]
I don't think this is an issue. As gparyani says, ClueBot already reverted the prior vandal edits, so we don't need to. Right?

**Comment by MusikAnimal** [comment]
And indeed, ClueBot uses rollback
