### ISSUE TITLE
Makefile should accept parameters for deploy

### ISSUE THREAD

**Issue by Huji** [azatoth/twinkle#285]
Makefile should be modified such that it would accept parameters for "make deploy" and pass them to the program it runs (i.e. sync.pl)

This can be achieved by changing the `deploy` section of Makefile to read:

````
deploy: twinkle.js morebits.js morebits.css $(modules)
        ./sync.pl ${ARGS} --deploy $^
````

Then one can run `make deploy` if they don't need to pass any parameters, or they can run `make ARGS="--lang=blah --family=foobar --u=SomeUser" deploy` to pass those parameters to the sync script..

**Comment by Huji** [comment]
Bumping this as it is a very simple yet useful change and has full backward compatibility.

**Comment by atlight** [comment]
I'll take your word for it :) As far as I know, only AzaToth uses this method of deployment. Amalthea and MusikAnimal use their own custom code.
