### ISSUE TITLE
Feature request for requests for closure

### ISSUE THREAD

**Issue by Tvx1** [azatoth/twinkle#289]
The Wikipedia has a notice board where you can request an uninvolved person to assess consensus and close discussions. I was wondering whether it would be possible to add a function to Twinkle so that you can submit such a request for closure of a discussion more swiftly.

**Comment by Amorymeltzer** [comment]
I've been thinking about this, but WP:ANRFC isn't used particularly broadly, and is probably better suited to manual, non-semi-automated additions.
