### ISSUE TITLE
Possible collaboration with Community Tech (WMF)

### ISSUE THREAD

**Issue by fhocutt** [azatoth/twinkle#290]
Community Tech is looking at some commonly used tools (https://phabricator.wikimedia.org/T108426 for Twinkle) and seeing if they are good candidates for us to help improve them while we're getting our team and processes set up. Some questions for Twinkle devs:
- Is there interest in Community Tech working on some of the open issues?
- Are there existing development plans or priorities we should be aware of?
- What is Twinkle currently licensed under?
- Has there been discussion about bringing some of these features into an extension?

**Comment by atlight** [comment]
I have commented at the [Phabricator task](https://phabricator.wikimedia.org/T108426#1538242).

**Comment by fhocutt** [comment]
Thanks, @atlight. I'll continue this there.

**Comment by Amorymeltzer** [comment]
Per [phab:T110148](https://phabricator.wikimedia.org/T110148), closing this has it has largely circled back to #129, lofty and far-off though it may be.  See #252 and #253 for license questions.
