### ISSUE TITLE
Add {{Histmerge}}

### ISSUE THREAD

**Issue by Kharkiv07** [azatoth/twinkle#293]
Add {{Histmerge}} to the standard tag set.

**Comment by atlight** [comment]
History merge is part of the G6 speedy deletion criterion, so the history merge tag is accessed via the CSD module.

You're not the first person to ask for this to added to the Tag module though. Do you think it should be available from both places?

**Comment by Kharkiv07** [comment]
I wouldn't have thought to look there, but I do see it now. I think there's a misunderstanding on what the G6 is for, however. WP:How to fix cut-and-paste moves says to use that tag UNLESS "no changes since the copied-from revision in either the original page or the pasted-to page", and {{db-copypaste}} specifies that it's for a clean page move. So, I see no harm duplicating it
