### ISSUE TITLE
Twinkle is not working in article space and file space

### ISSUE THREAD

**Issue by McMatter78** [azatoth/twinkle#294]
As of October 1, 2015 Twinkle has stopped working in the some of article and file space for many users. The TW menu does not show up at all. A couple examples are https://en.wikipedia.org/wiki/Jane_Bordeaux twinkle does not show up, but https://en.wikipedia.org/wiki/Middle_East_University_%28Jordan%29 does

**Comment by atlight** [comment]
Yes, I saw this discussion at WP:VPT. I'll come over and have a look.

Is it only article and file space? That doesn't make a whole lot of sense. Maybe the tag module is playing up, since it is only active in those two NSs.

**Comment by McMatter78** [comment]
I just altered my original comment, it seems to pick certain articles, I gave 2 examples above one that works and one that doesn't

**Comment by atlight** [comment]
Per Stefan2's comment `and other scripts have been failing too` on WT:TW, I'm led to think this is part of a broader Wikipedia, WMF-cluster or MediaWiki problem relating to the loading of scripts.

**Comment by atlight** [comment]
See Phabricator task T114462
