### ISSUE TITLE
TW incorrectly deletes a page as a redirect to a CSD target when it is not.

### ISSUE THREAD

**Issue by HighInBC** [azatoth/twinkle#296]
I used twinkle to delete https://en.wikipedia.org/w/index.php?title=Ruben_Correa per G10. It deleted https://en.wikipedia.org/wiki/User_talk:Rjwilmsi on that basis that it was a redirect to that article, however it was not. This was the state of the page when it was deleted: [https://en.wikipedia.org/w/index.php?title=User_talk:RjwilmsiBot&oldid=686505612].

The bug appears to be in not realizing the redirect is separate from the message below the redirect.

**Comment by azatoth** [comment]
The modules uses the query/backlinks API to get the redirects; it doesn't parse the page at all; so if something went wrong, it's due to MW borking out. see https://github.com/azatoth/twinkle/blob/master/modules/twinklespeedy.js#L1136-L1187

**Comment by azatoth** [comment]
Is MW bug https://phabricator.wikimedia.org/T115917

**Comment by atlight** [comment]
Not a MW bug; twinkle should use prop=redirects instead of list=backlinks.

**Comment by azatoth** [comment]
whoops

**Comment by atlight** [comment]
Fixed by ae6802e25bddd6319c4250ea8116a9bbea1b1a24 (`speedy`, thanks to @MusikAnimal) and e3ed44f23c998c7431f23a94365984b0a57c97ca (`batchdelete` and `deprod`).
