### ISSUE TITLE
Add support for Special:ComparePages

### ISSUE THREAD

**Issue by he7d3r** [azatoth/twinkle#308]
Please enable it also on pages such as
https://en.wikipedia.org/wiki/Special:ComparePages?page1=&rev1=698181148&page2=Wikipedia%3ASandbox&rev2=&action=&diffonly=&unhide=
where right now only the default "undo" and "[rollback N edits]" are available.

**Comment by Amorymeltzer** [comment]
Isn't ComparePages mostly for diffing two different pages?  I think the case where someone is using it to diff the same page is rather rare, and probably not worth the effort to rewrite the `twinklefluff` module given the pitfalls.
