### ISSUE TITLE
Bug: Second AfD relisting in the same day

### ISSUE THREAD

**Issue by Finngall** [azatoth/twinkle#313]
Greetings. I have noticed an undesirable behavior when a Twinkle user attempts to relist an AfD discussion after it has already been relisted on that day, usually due to an edit conflict. Twinkle normally quite handily comments out the active listing from the previous daily log page and relists it on the current day's log page, but when the active listing is already on the current day's page, it comments it out there and does nothing else, thereby making it disappear. I usually find them only via Wikipedia:Article alerts/Problem entries/Old, where a bot collects listings that are over a month old.

**Comment by atlight** [comment]
I'm sorry, I saw your post at WT:TW but neglected to reply to it.

Twinkle does not offer AfD relisting functionality. `User:Mr.Z-man/closeAFD ` might be the script in question here.
