### ISSUE TITLE
Template:New unreviewed article

### ISSUE THREAD

**Issue by zanhecht** [azatoth/twinkle#330]
The description of {{New unreviewed article}} in Twinkle is a bit misleading, and leads to the sort of abuse that caused the template to be nominated at TfD. The template documentation says "It should never be placed on someone else's article under any circumstances", but the Twinkle description just says "mark article for later review >", which strongly implies that it is for marking other editor's articles that you plan on reviewing later.

The easiest solution is just to remove this template from Twinkle altogether. This template is mostly designed to be used by the Article Wizard, but users can also place it on their own articles. However, an editor who is advanced enough to be using Twinkle is very unlikely to every need to use this tag, as they are also likely experienced enough not to need to tag their new article for review.

If the template is kept, is Twinkle smart enough to only place it on articles created by the user? If not, the description should be changed to read "mark your own article for later review >" and/or pop up an "are you sure?"-type warning.

**Comment by JadeMaveric** [comment]
I new, so I'm not sure if Twinkle is smart enough to check if is smart enough to check. But at any rate. the description definitely needs to be changed.

**Comment by JadeMaveric** [comment]
I reworded the message to "mark (your own) article for later review".
Umm... can someone give me directions to commit to the remote repo?

**Comment by atlight** [comment]
> Umm... can someone give me directions to commit to the remote repo?

You have to file a [pull request](https://help.github.com/articles/proposing-changes-to-a-project-with-pull-requests/).

**Comment by JadeMaveric** [comment]
@atlight thanks, I'll do it after school today.
