### ISSUE TITLE
CSD criteria for user pages not shown if they are redirects

### ISSUE THREAD

**Issue by nyuszika7h** [azatoth/twinkle#335]
On https://en.wikipedia.org/w/index.php?title=User:Nyuszika7H/sandbox1&redirect=no Twinkle does not offer any of the the user page criteria for CSD, presumably because it's a redirect, as it works fine on https://en.wikipedia.org/w/index.php?title=User:Nyuszika7H/sandbox2.

**Comment by siddharthvp** [comment]
@Close this. U1 and U2, which are the only U* criteria that can be applicable for redirects, are now shown.
