### ISSUE TITLE
Wording of Twinkle's CSD responses

### ISSUE THREAD

**Issue by KdsGit** [azatoth/twinkle#337]
I am new to GitHub, and am hoping I am jumping in at the right place for this: I have been using Twinkle for a few months now, and finding it extremely useful.  Occasionally, however, it blindsides me: I will be going through a list of possible reasons for speedy deletion, select one I have either never used before or which I have used very seldom but which seems to be the correct/ appropriate option, and then approved my decision.  What then pops up on the to-be-deleted page sometimes seems MUCH more (or much LESS) emphatic than I intended, or does not actually address the subject the way I though it would.  I realize that there are the one-sentence summaries which are meant to help editors choose between A2 and A3, but that doesn't always cover the bases.  Here's an example: criterion A7 when selected for an organization.  If you select this option but happen to be nominating an educational institution, the resulting speedy deletion tag contradicts you— and you have no way of knowing it will do this until after it has already been done! (unless you happen to know beforehand that A7 can't be used for educational institutions).  There is nothing in the one-sentence summary or even in the hover-questionmark help balloon that tells you that A7 can't be used for educational institutions.  Can we get it changed so that it warns editors NOT to used A7 for such institutions?  I think there are other examples of such surprises, but that one comes to mind first.  As I am not even certain this is the right venue for making this suggestion, I will end here and see what happens.  Thanks for considering the request.

**Comment by atlight** [comment]
Theoretically you are expected to have read and digested WP:CSD before using Twinkle's CSD module, as implied by the large warning box at the top of the Gadgets selection page in your Preferences and at WP:TW. The summaries in the CSD dialog box are only meant as reminders or memory-joggers. Having said that, it might be good to have a look and make sure those tooltips reflect the modern reality, since they haven't really been touched since 2011.

**Comment by KdsGit** [comment]
That would be great! (I have read over all of the CSD criteria in the past— it's just that I sometimes forget specific details of one or the other and I don't like making mistakes any more than the next guy...  We learn things, we forget things, we like it when there are tools that cover our butts when we forget things we know we shouldn't, that sort of thing).

**Comment by QEDK** [comment]
@KdsGit would you like to work with me on this, I can make the necessary changes and submit a pull request as we work on the wording?

**Comment by KdsGit** [comment]
Absolutely!  Just let me know how and count me in!

**Comment by QEDK** [comment]
@KdsGit Let's just continue this conversation on my talk page (my enwiki user ID is the same as the one here). Just give me a list of your suggested changes as the first measure, we'll work on that.

**Comment by Amorymeltzer** [comment]
Stale issue, but improvements to match policy always welcome
