### ISSUE TITLE
Ability to load external Twinkle modules

### ISSUE THREAD

**Issue by tom29739** [azatoth/twinkle#345]
I think you used to be able to load extra modules for Twinkle somewhere, but this functionality got removed.
It would be useful to be able to load additional modules into Twinkle, from the user's common.js, or the preferences window.
Developers could then use Twinkle's features such as the menus in their own scripts and integrate them into Twinkle.

**Comment by MusikAnimal** [comment]
I'm not aware of any pre-existing functionality like this. If developers want to incorporate their own module, they can do so like the existing ones:
```
Twinkle.addPortletLink( Twinkle.myModule.callback, 'My Module', 'tw-my-module', 'Tooltip for my module' );
Twinkle.myModule.callback = function twinkleMyModuleCallback() {
   ...code...
}
```
The function names are a convention but can be whatever you want. The [Twinkle.addPortletLink](https://github.com/azatoth/twinkle/blob/master/twinkle.js#L320) is what adds the link, you can do whatever you want from there. Note everything is in the global scope, so if you want to use a function in another Twinkle module it should be available to you.

**Comment by atlight** [comment]
There's [`Twinkle.initCallbacks`](https://github.com/azatoth/twinkle/blob/master/twinkle.js#L30-L34) in twinkle.js, but I don't know if it actually works.

**Comment by Amorymeltzer** [comment]
Per above, this is already possible (see [here](https://en.wikipedia.org/wiki/User:Bellezzasolo/Scripts/arb) for an example).
