### ISSUE TITLE
Don't notify indef-blocked users about deletion requests

### ISSUE THREAD

**Issue by OdMishehu** [azatoth/twinkle#346]
In all deletion processes, it's customary to notify the original author, and Twinkle handles this. One exception, however, is that there is no reason to notify an indef-blocked user; please make Teinkle not notify them when their pages are being put up for deletion. See also https://en.wikipedia.org/w/index.php?title=Wikipedia:Village_pump_(technical)&oldid=726196838#Notices_on_banned_users.27_talk_pages

**Comment by atlight** [comment]
I'm not sure that I agree; "indefinitely blocked" doesn't mean "blocked forever". The user may later be unblocked and wish to follow up on the deletion notices that were issued during the block. Depending on the circumstances, they may well be unblocked very soon after the block is issued. So it's not true that there is "no reason" to notify these users. Even indefinitely banned users are unbanned sometimes.

**Comment by OdMishehu** [comment]
They rarely are; on the other hand, their pafges end up full of these warnings, and I suspect that these are some times temptations to try and bypass the rules with sockpupets. See also The discussion I linked to above.

**Comment by Amorymeltzer** [comment]
I think this is a big enough change in expected behavior that there should be an on-wiki conversation first.  I agree that it'd be nice if Twinkle were more respectful of retired, deceased, etc. editors, but the messages *are* expected and can be helpful to others.
