### ISSUE TITLE
Populate diff= parameter for uw-npa series

### ISSUE THREAD

**Issue by mattflaschen** [azatoth/twinkle#349]
This is a feature request.  I've added an optional diff= parameter to the uw-npa series (e.g. https://en.wikipedia.org/wiki/Template:Uw-npa1), to specify the URL of the edit containing the personal attack.

It would be nice if Twinkle populated that when you rolled back an edit through Twinkle, then they opened the user warning dialog.

I'm not positive, but it doesn't look like this is done for any other user warning templates either, so this might require some infrastructure.

**Comment by siddharthvp** [comment]
Should be do-able by adding the diff and oldid parameters to the url, for Twinkle to access. But I wonder if this is worth doing, should we really link to personal attacks?

**Comment by Amorymeltzer** [comment]
Thought I closed this the other day, for just that reason.  If this sort of thing is indeed desired by the community, as OP says there's some infrastructure needed first.
