### ISSUE TITLE
"Requesting history merge with undefined"

### ISSUE THREAD

**Issue by nyuszika7h** [azatoth/twinkle#350]
Not sure what happened [here](https://en.wikipedia.org/w/index.php?title=Thomas_Bain_(Orange)&diff=prev&oldid=734666198), but at least it added the article name in the `{{db-histmerge}}` tag correctly.

**Comment by MusikAnimal** [comment]
Fixed with a683c76a5b5e79558ec9bbfc22fb9338f5c602af. Thanks!
