### ISSUE TITLE
Twinkle Not Loading

### ISSUE THREAD

**Issue by DatGuy1** [azatoth/twinkle#351]
When I am reading an article, Twinkle occasionally doesn't show up. Same when I am viewing a diff. However, if I am in edit mode or viewing the history, then it does show up

**Comment by Technical-13** [comment]
@DatGuy1 which browser are you using?  Do you know how to pull up the JavaScript error console in your browser?  What other gadgets/userscripts are you using?  Thanks.

**Comment by DatGuy1** [comment]
I am using Google Chrome. Not sure what the error console is. Is it the thing that opens when you do ctrl+shift+J? My common.js has 
`importScript('User:Anomie/watchlist-change-style-selector.js'); // Linkback: [[User:Anomie/watchlist-change-style-selector.js]]
importStylesheet('User:Anomie/watchlist-change-style-selector.css'); // Linkback: [[User:Anomie/watchlist-change-style-selector.css]]
importScript('User:Equazcion/ScriptInstaller.js');
importScript('User:PleaseStand/userinfo.js'); //Linkback: [[User:PleaseStand/userinfo.js]] Added by Script installer
importScript('User:Equazcion/DynaThank.js'); //Linkback: [[User:Equazcion/DynaThank.js]] Added by Script installer
importScript('User:Zhaofeng Li/Reflinks.js'); //Linkback: [[User:Zhaofeng Li/Reflinks.js]] Added by Script installer
importScript('User:NuclearWarfare/Mark-blocked script.js'); //Linkback: [[User:NuclearWarfare/Mark-blocked script.js]] Added by Script installer
importScript('User:Equazcion/ContribsTabVector.js'); //Linkback: [[User:Equazcion/ContribsTabVector.js]] Added by Script installer
importScript('User:Gary/highlight my username in history.js'); //Linkback: [[User:Gary/highlight my username in history.js]] Added by Script installer
importScript('User:Writ Keeper/Scripts/deletionFinder.js'); //Linkback: [[User:Writ Keeper/Scripts/deletionFinder.js]] Added by Script installer
importScript('User:Ais523/watchlistnotifier.js'); //Linkback: [[User:Ais523/watchlistnotifier.js]] Added by Script installer
importScript( 'User:APerson/delsort.js' );// Backlink: [[User:APerson/delsort.js]]
importScript('User:Ais523/votesymbols.js'); //Linkback: [[User:Ais523/votesymbols.js]] Added by Script installer
importScript('User:Epicgenius/pcreview.js'); //Linkback: [[User:Epicgenius/pcreview.js]] Added by Script installer
importScript('User:Mr. Stradivarius/gadgets/Draftify.js'); // Linkback: [[User:Mr. Stradivarius/gadgets/Draftify.js]]
importScript('User:Anomie/ajaxpreview.js'); //Linkback: [[User:Anomie/ajaxpreview.js]] Added by Script installer
importScript('User:Anomie/unwatch.js'); //Linkback: [[User:Anomie/unwatch.js]] Added by Script installer
importScript('User:Nageh/rollbackSum.js'); //Linkback: [[User:Nageh/rollbackSum.js]] Added by Script installer
importScript('User:Writ Keeper/Scripts/massRollback.js'); //Linkback: [[User:Writ Keeper/Scripts/massRollback.js]] Added by Script installer
importScript('User:Czar/closexfd.js'); //Linkback: [[User:Czar/closexfd.js]] Added by Script installer`

**Comment by Technical-13** [comment]
For clarity -- http://enwp.org/User:DatGuy/common.js
```
	importScript( 'User:Anomie/watchlist-change-style-selector.js' ); // Linkback: [[User:Anomie/watchlist-change-style-selector.js]]
	importStylesheet( 'User:Anomie/watchlist-change-style-selector.css' ); // Linkback: [[User:Anomie/watchlist-change-style-selector.css]]
	importScript( 'User:Equazcion/ScriptInstaller.js' );
	importScript( 'User:PleaseStand/userinfo.js' ); //Linkback: [[User:PleaseStand/userinfo.js]] Added by Script installer
	importScript( 'User:Equazcion/DynaThank.js' ); //Linkback: [[User:Equazcion/DynaThank.js]] Added by Script installer
	importScript( 'User:Zhaofeng Li/Reflinks.js' ); //Linkback: [[User:Zhaofeng Li/Reflinks.js]] Added by Script installer
	importScript( 'User:NuclearWarfare/Mark-blocked script.js' ); //Linkback: [[User:NuclearWarfare/Mark-blocked script.js]] Added by Script installer
	importScript( 'User:Equazcion/ContribsTabVector.js' ); //Linkback: [[User:Equazcion/ContribsTabVector.js]] Added by Script installer
	importScript( 'User:Gary/highlight my username in history.js' ); //Linkback: [[User:Gary/highlight my username in history.js]] Added by Script installer
	importScript( 'User:Writ Keeper/Scripts/deletionFinder.js' ); //Linkback: [[User:Writ Keeper/Scripts/deletionFinder.js]] Added by Script installer
	importScript( 'User:Ais523/watchlistnotifier.js' ); //Linkback: [[User:Ais523/watchlistnotifier.js]] Added by Script installer
	importScript( 'User:APerson/delsort.js' );// Backlink: [[User:APerson/delsort.js]]
	importScript( 'User:Ais523/votesymbols.js' ); //Linkback: [[User:Ais523/votesymbols.js]] Added by Script installer
	importScript( 'User:Epicgenius/pcreview.js' ); //Linkback: [[User:Epicgenius/pcreview.js]] Added by Script installer
	importScript( 'User:Mr. Stradivarius/gadgets/Draftify.js' ); // Linkback: [[User:Mr. Stradivarius/gadgets/Draftify.js]]
	importScript( 'User:Anomie/ajaxpreview.js' ); //Linkback: [[User:Anomie/ajaxpreview.js]] Added by Script installer
	importScript( 'User:Anomie/unwatch.js' ); //Linkback: [[User:Anomie/unwatch.js]] Added by Script installer
	importScript( 'User:Nageh/rollbackSum.js' ); //Linkback: [[User:Nageh/rollbackSum.js]] Added by Script installer
	importScript( 'User:Writ Keeper/Scripts/massRollback.js' ); //Linkback: [[User:Writ Keeper/Scripts/massRollback.js]] Added by Script installer
	importScript( 'User:Czar/closexfd.js' ); //Linkback: [[User:Czar/closexfd.js]] Added by Script installer
```

Yes, in Chrome, `CTRL`-`SHIFT`-`J` opens the error console.  If you could take a screenshot of whatever is in there to post here, that'd be very helpful.  Thanks.

**Comment by DatGuy1** [comment]
Clearing the cache and restarting my computer fixed it.

**Comment by DatGuy1** [comment]
I believe that it is something with Java. I just 'updated' my Java and it became broken again. [http://imgur.com/a/9aizd](Screenshot of console). Would it help to know my Java version?

**Comment by atlight** [comment]
Twinkle does not use Java.

You have an alarming number of scripts, many of which are very old, in your common.js. I would highly recommend that you remove all your scripts from common.js, and see if Twinkle appears reliably for you. If that fixes the problem, re-add your scripts to common.js piecemeal, and use the process of elimination to find the script that is causing the trouble.

**Comment by Technical-13** [comment]
Mostly what @atlight said, only expand that to include clearing your https://en.wikipedia.org/wiki/User:DatGuy/vector.js and putting those back one at a time as well.

**Comment by DatGuy1** [comment]
I've just removed all my scripts from common.js, vector.js, monobook.js (even though I use vector), and global.js but it still doesn't work. I also disabled all my extensions and cleared my cache. Still, Twinkle doesn't work (I also purged the cache every time)

**Comment by DatGuy1** [comment]
With the console, I can see that it says "Use of importScript URI is deprecated. Use mw.loader instead. How do I fix that?

**Comment by DatGuy1** [comment]
Alright. I've changed my language from en-gb to en, and so far it works fine. I'll close this if there are no problems for a day or two

**Comment by DatGuy1** [comment]
Changing it from en-gb to en fixed it. @Technical-13 , any idea why that happened?
