### ISSUE TITLE
{{spamblacklistblock}} option

### ISSUE THREAD

**Issue by djbeetstra** [azatoth/twinkle#354]
For admins, in Twinkle there is the block option, which automatically blocks editors with some pre-set options, and tags the talkpage of the editor.  

Since I find myself blocking 'spambots' on a regular (daily) basis, I'd like this option to be enabled in Twinkle - now I select 'block' on the editor, select {{spamblacklistblock}} from the pull-down, disable talkpage access (as they very often continue to spam their talkpages), and choose to watch the user, and block them (generally for at least 1 month).  I then tag the talkpage of the user with {{subst:spamblacklistblock}} so if ever the IP gets re-used by a regular, it has some note as to why they can't edit.  Thanks.

**Comment by MusikAnimal** [comment]
Done
