### ISSUE TITLE
XfD tagging should leave a newline between the tag and a table afterwards

### ISSUE THREAD

**Issue by jc86035** [azatoth/twinkle#359]
Twinkle's XfD tagging tends to mess up pages (particularly templates) that begin with tables, because it doesn't insert a newline before the table. This could probably be fixed by checking if a page begins with `{|`.

**Comment by jc86035** [comment]
According to Uanfala on English Wikipedia, this also happens with section headers.

**Comment by jc86035** [comment]
I'm guessing this might also happen with lists `*` `#` and our fake indents that aren't actually indents `:`.

**Comment by Amorymeltzer** [comment]
This does indeed happen with template tables, but this behavior intentional; see #254 — newlines are significant and may themselves be undesirable.  I think it's basically six and one half-dozen which is better, but I think leading tables in templates are the more rare occurrence.

**Comment by Amorymeltzer** [comment]
>checking if a page begins with `{|`

Reopening as this should be simple (famous last words...) and since this has [come up again](https://en.wikipedia.org/w/index.php?oldid=886646532#Twinkle_TFDs_breaking_tables); pr soon.

**Comment by Amorymeltzer** [comment]
[Discussion seems to be coalescing](https://en.wikipedia.org/w/index.php?oldid=886765882#Twinkle_TFDs_breaking_tables) around inserting the newline for `standard` and `sidebar` styles, as the newline should only(?) be an issue for the two inline options.
