### ISSUE TITLE
Add {{Weclome to Wikipedia}} to the welcoming templates

### ISSUE THREAD

**Issue by najjara** [azatoth/twinkle#361]
`{{Welcome to Wikipedia}}` is elegant and looks noobie friendly and non-threatening. It looks better than `{{welcome-graphical}}` or `{{welcome-menu}}`. Can we please have it added to the standard welcoming templates?

**Comment by atlight** [comment]
See https://en.wikipedia.org/wiki/Wikipedia_talk:Twinkle/Archive_38#.7B.7BWelcome_to_Wikipedia.7D.7D
