### ISSUE TITLE
Double loading styles

### ISSUE THREAD

**Issue by LunarTwilight** [azatoth/twinkle#362]
Found this in my console:
`Gadget "Twinkle" styles loaded twice. Migrate to type=general. See <https://phabricator.wikimedia.org/T42284>.`

**Comment by MusikAnimal** [comment]
Fixed by updating the gadget definition ([diff](https://en.wikipedia.org/w/index.php?title=MediaWiki:Gadgets-definition&diff=747063900&oldid=742370678)). Thanks
