### ISSUE TITLE
Expiry param no longer needed in protection templates

### ISSUE THREAD

**Issue by CenariumEnwiki** [azatoth/twinkle#363]
The expiry of pages under protection or pending changes is now automatically detected by the protection template, so Twinkle no longer has to add it as a param when adding the protection template.
See https://en.wikipedia.org/wiki/Module:Effective_protection_expiry.

**Comment by Amorymeltzer** [comment]
If I'm reading https://en.wikipedia.org/wiki/Module:Protection_banner correctly, the use of `expiry` in the template doesn't even avoid any expensive calls, as {{pp}} and all the related templates just call `{{#invoke:Protection banner|main}}`.  Is there even a need to do... anything?  Theoretically Twinkle needs to ask about noinclude and whether to iconify, and then just use `{{pp}}` in all cases.

In practice, I feel this probably warrants some discussion, though I'm not sure where.  I certainly like having the explicit tags, and I imagine other editors find it helpful to see a vague reason (blp, vandalism, move, etc.) and the expiration when editing.

**Comment by Amorymeltzer** [comment]
Looks like the protection banner doesn't (currently?) handle the type of protection correctly.  That is, `{{pp}}` only works if there is edit protection on; it's busted if PC or just move is on.  Expiry should be fine though.
