### ISSUE TITLE
Group inside {{multiple issues}} not working

### ISSUE THREAD

**Issue by super3588** [azatoth/twinkle#365]
Ever since I started using Twinkle's tagging feature, I've noticed that, even when I have the aforementioned checkbox checked, Twinkle does not attempt to put the templates I've selected inside {{multiple issues}}, so I have to go do it myself.  Twinkle doesn't even add the {{multiple issues}} template to the page anywhere.

**Comment by atlight** [comment]
Can you show some diffs?

**Comment by super3588** [comment]
@atlight An example of that would be [here](https://en.wikipedia.org/w/index.php?title=NES_Classic_Edition&diff=prev&oldid=749032304).  After examining my recent edits, I've noticed that it doesn't do it all the time.  The only notable difference I've noticed between this diff and the others is the {{distinguish}} tag that was already on the page.

**Comment by atlight** [comment]
This is the positively antique issue #13, which is actually somewhat non-trivial to fix. I'll have to look into it again at some point.
