### ISSUE TITLE
Allow custom templates to be added to existing categories 

### ISSUE THREAD

**Issue by p1xels** [azatoth/twinkle#369]
This would make things a lot easier, especially with welcoming where there are templates for anon users and nonanon users that get automatically selected based on if they are anon and nonanon.

**Comment by siddharthvp** [comment]
Suggest closure, as it's not clear what is being asked. And it's too late to ask for a clarification.

Welcome module already supports custom tags FWIW.

**Comment by Amorymeltzer** [comment]
I _think_ this is referring to allowing custom tags to be added to the already-existing categories, such as in warnings.  I suppose we could technically provide a dropdown in preferences for users to select which category they want a notice to fit into?  I think it's unlikely to be widely desired, though, and would prefer consensus on-wiki first, especially re: #491
