### ISSUE TITLE
Option to not open every time the discussion page (XFD)

### ISSUE THREAD

**Issue by XXN** [azatoth/twinkle#371]
Please add an option to not load & open every time the discussion page, when starting XFDs, MFDs, AFDs, etc. Sometimes users work on a list of pages and they really don't need to see the each time the discussion page they created. At `Files for discussion` some users start by 10-15 consecutive FFDs - do you think they need to see each time the FFD page?

**Comment by XXN** [comment]
Or, [around 50 times a day Twinkle loaded the FFD daily subpage for me without my permission](https://en.wikipedia.org/w/index.php?title=Wikipedia:Files_for_discussion/2017_April_11&offset=20170412015408&limit=54&action=history). It's annoying.

**Comment by Amorymeltzer** [comment]
I've gone through the daily logs for the past two-three months, this is rare.  There were only a couple of times where this would be helpful or useful.
