### ISSUE TITLE
Feature request: append-only support for Flow talk pages

### ISSUE THREAD

**Issue by Artoria2e5** [azatoth/twinkle#373]
Twinkle ported to other wikis where flow is enabled frequently encounters failures with Flow-based user talk pages. It appears that the [`new-topic`](https://www.mediawiki.org/wiki/Extension:Flow/API#new-topic) submodule in Flow's API is simple enough to be smuggled into Twinkle without any extra knowledge of Flow's model. The resulting dumb, append-by-new-topic-only support should be a "good enough" relief for folks over zhwp (like me).

**Comment by Amorymeltzer** [comment]
See #251; better to deal with flow/etc. in one fell swoop
