### ISSUE TITLE
Please add warn and block modules to Special:DeletedContributions

### ISSUE THREAD

**Issue by MER-C** [azatoth/twinkle#374]
I find myself wanting to warn a user or reach for the banhammer on review of their deleted contributions fairly often. Right now, this is a two step process (click on user page/talk page/contribs, then warn/block) when it can easily be one.

**Comment by MusikAnimal** [comment]
Done! https://github.com/azatoth/twinkle/commit/adce3082c4812a389cdce298549675a712a76a5d
