### ISSUE TITLE
"Replacing other user talks" broken in Firefox 52

### ISSUE THREAD

**Issue by John-of-Reading** [azatoth/twinkle#375]
The option to open talk pages "In a window, replacing other user talks" is broken after upgrading to Firefox 52 or 52.0.1. Each user talk page opens in yet another new window.

Reported by NeilN at https://en.wikipedia.org/wiki/Wikipedia_talk:Twinkle#Open_user_talk_page_after_these_types_of_reversions

**Comment by Amorymeltzer** [comment]
Per https://en.wikipedia.org/wiki/Wikipedia_talk:Twinkle/Archive_39#Open_user_talk_page_after_these_types_of_reversions this was due to a browser extension.
