### ISSUE TITLE
Add support for file PROD

### ISSUE THREAD

**Issue by Samwalton9** [azatoth/twinkle#376]
The English Wikipedia has supported using Proposed Deletion on files (https://en.wikipedia.org/wiki/Wikipedia_talk:Proposed_deletion#File_PROD), so Twinkle should support adding PROD tags to file pages. The template details are still being finalised, so I'll update here when we know which template is being used and how.

**Comment by MusikAnimal** [comment]
Done with [this edit](https://en.wikipedia.org/w/index.php?title=MediaWiki:Gadget-twinkleprod.js&diff=772475686&oldid=771450686), but I haven't pushed the changes to GitHub yet... I've got some mysterious SSH issues going on. Leaving this open for now

**Comment by MusikAnimal** [comment]
Done with 5fdce5b2241a0a4d8c52fb4dd844b2481ef39ae0
