### ISSUE TITLE
Issue at FFD

### ISSUE THREAD

**Issue by XXN** [azatoth/twinkle#380]
Adding a new FFD entry in the daily FFD subpage, Twinkle replaced another FFD entry instead of appending the new one. Diff: https://en.wikipedia.org/w/index.php?title=Wikipedia:Files_for_discussion/2017_April_10&diff=774835868&oldid=774835864

**Comment by XXN** [comment]
@atlight [this commit](https://github.com/azatoth/twinkle/commit/909a4cb4a0bfbb28858e192fb93f8167abca644b) should fix this issue, right?

**Comment by atlight** [comment]
I made that commit (and it was [synced on wiki](https://en.wikipedia.org/w/index.php?title=MediaWiki:Gadget-twinklexfd.js&diff=714898978&oldid=714670905)) more than a year ago, so if the issue is still ongoing, then something else is going wrong.
