### ISSUE TITLE
jquery.ui

### ISSUE THREAD

**Issue by LunarTwilight** [azatoth/twinkle#384]
Twinkle throws the following errors in console:

`This page is using the deprecated ResourceLoader module "jquery.ui.core".
Please use "mediawiki.ui.button" or "oojs-ui" instead.`

`This page is using the deprecated ResourceLoader module "jquery.ui.position".`

`This page is using the deprecated ResourceLoader module "jquery.ui.widget".`

**Comment by atlight** [comment]
We don't have any plans to move away from jQuery UI at the moment. The fatal flaw of OOjs UI is that it doesn't allow the user to move dialogs around on the page, which is critical for Twinkle.

**Comment by LunarTwilight** [comment]
I might be wrong, and I probably am, but wouldn't buttons and etc not affect the dialogs being movable?

**Comment by atlight** [comment]
We use jQuery UI for Twinkle's dialogs. Although `jquery.ui.dialog` doesn't appear to have been explicitly deprecated, it depends on the three modules you've listed, so we would need to replace jQuery UI dialogs with OOjs UI dialogs in order to avoid the deprecation warnings.
