### ISSUE TITLE
Feature request:  Better templating of sock masters / puppets

### ISSUE THREAD

**Issue by GoldenRingWP** [azatoth/twinkle#386]
It'd be nice if the option to block as a sockpuppet took the master account as a parameter and left the appropriate {{sockpuppet|<master account>|blocked}} template on the user page.

If I get a bit of free coding time I could have a go at this myself, though that's not looking likely any time soon.

**Comment by Amorymeltzer** [comment]
@GoldenRingWP Do you still think this would be helpful?  I go back and forth on whether this would be helpful or just encourage more tagging, which maybe wouldn't be a great idea per DENY?  It's been a decade since I was active at SPI, though.

**Comment by Xi-Plus** [comment]
I have implemented similar functions on zhwiki's Twinkle.
Sample: https://zh.wikipedia.org/w/index.php?diff=56623508 (Tagging with {{Blocked user}} template).

![image](https://user-images.githubusercontent.com/7577245/67643939-bf644000-f957-11e9-8ea3-d6e5597861d6.png)

**Comment by siddharthvp** [comment]
It might help to consult CUs about this, IIRC some of them like Bbb have pretty strong opinions on the appropriateness of tagging. 

I think theoretically it would be it good to have a checkbox that's unchecked by default (and for which there's no preference option to make it checked by default).

**Comment by Amorymeltzer** [comment]
>It might help to consult CUs about this

I did earlier this year, the couple I spoke with were pretty meh on the idea.  Thought I closed this at the time...

**Comment by Amorymeltzer** [comment]
Deciding against this after some further thought and discussions elsewhere.
