### ISSUE TITLE
MfD Issue

### ISSUE THREAD

**Issue by Pix1234** [azatoth/twinkle#388]
On the deletion discussion page it doesnt properly setup the page links and page title (header) 
for example this [diff](https://en.wikipedia.org/w/index.php?title=Wikipedia:Miscellany_for_deletion/Wikipedia:Churnalism&diff=next&oldid=793622776)

**Comment by atlight** [comment]
It [worked for me](https://en.wikipedia.org/wiki/Wikipedia:Miscellany_for_deletion/User:This,_that_and_the_other/sandbox). Is it possible you had an error in the wiki syntax of your reason? This can sometimes cause the template substitution to get screwed up.

**Comment by Pix1234** [comment]
Unlikely, because i didnt have any syntax that would interfer...

Thanks,
Zppix
Volunteer Developer for WMF
www.enwp.org/User:Zppix

**Comment by atlight** [comment]
Right, well, we'll keep an eye on it. Post back here if you see it happen again.
