### ISSUE TITLE
False Positive Deletion template detected when attempting to speedy

### ISSUE THREAD

**Issue by hasteur** [azatoth/twinkle#391]
Page: https://en.wikipedia.org/w/index.php?title=Draft:Brett_Rossi&oldid=727816046

Offending template invocation:  {{afdb name|id=60887|gender=female|name=Brett Rossi}}

Offending code lines from modules/twinklespeedy.js:
var xfd = /(?:\{\{([rsaiftcm]fd|md1|proposed deletion)[^{}]*?\}\})/i.exec( text );
			if( xfd && !confirm( "The deletion-related template {{" + xfd[1] + "}} was found on the page. Do you still want to add a CSD template?" ) ) {
				return;
			}

In this case {{afd is matched so a negative case to disclude the Adult Film DataBase template should be added.

**Comment by atlight** [comment]
We could just add `\b` after the parenthesis:

`var xfd = /(?:{{([rsaiftcm]fd|md1|proposed deletion)\b[^{}]*?}})/i.exec( text );`

Actually this regex needs to be updated; it seems like we place `{{article for deletion/dated` on AFD nominations now.

**Comment by hasteur** [comment]
Entirely your call as to how to resolve it.  Just following the procedure for reporting what I think is a bug
