### ISSUE TITLE
Testing twinkle

### ISSUE THREAD

**Issue by GoldenRingWP** [azatoth/twinkle#392]
Can someone please give me a quick pointer to how to set up a twinkle fork in my userspace, for testing purposes?

I'm not sure, but README.md makes it look like `sync.pl --deploy` will try to overwrite the site-wide Twinkle installation, while `sync.pl --push *.js *.css modules` tells me `Can't call method "edit" on an undefined value at ./sync.pl line 109.`

I've set up `~/.mwbotrc` with a bot password with "Basic rights," "Edit your user CSS/Javascript" and "Create, edit and move pages" rights.

What am I doing wrong?

**Comment by MusikAnimal** [comment]
@GoldenRingWP I would open up your JS console and copy/paste in the code for whatever module you're working on. That's how I do it, at least. You are also free to change the Twinkle source files on testwiki, but note you'll have to wait for the ResourceLoader cache to invalidate. You might be able to force it by by clearing your localStorage, can't remember.

**Comment by GoldenRingWP** [comment]
Ah, okay.  What is the `--base` option to `sync.pl` for then?

**Comment by MusikAnimal** [comment]
I've never used the sync script, but it's not meant for testing anyway. It's entirely possible that it doesn't work anymore.

**Comment by GoldenRingWP** [comment]
Okay, thanks.  I've started an RfA on testwiki (I want to work on the speedy module in sysop mode) but so far the tumbleweed is deafening...

**Comment by MusikAnimal** [comment]
I've made you a sysop there. Don't hesitate to ask me about the speedy module, a lot of that is my work. We might find a better venue to talk than GitHub issues, though :) Shoot me an email via Special:EmailUser or you can find me on IRC.
