### ISSUE TITLE
jQuery 3 migration warnings

### ISSUE THREAD

**Issue by evad37** [azatoth/twinkle#398]
On page load:
- [x] JQMIGRATE: jQuery.parseJSON is deprecated; use JSON.parse

On opening a dialog (e.g. to CSD a page):
- [ ] JQMIGRATE: jQuery.fn.bind() is deprecated
- [ ] JQMIGRATE: jQuery.fn.unbind() is deprecated
- [ ] JQMIGRATE: jQuery.fn.offset() requires a valid DOM element

When dragging a dialog:
- [ ] JQMIGRATE: jQuery.fn.andSelf() is deprecated and removed, use jQuery.fn.addBack()
- [ ] JQMIGRATE: jQuery.fn.offset() requires an element connected to a document

**Comment by mc10** [comment]
I believe the rest are due to jQuery UI; see also: #414.

**Comment by Amorymeltzer** [comment]
MediaWiki has 1.9.2 installed, and it looks like 1.12 is when jquery.ui took care of these.

I can't see it, but I think [T71386](https://phabricator.wikimedia.org/T71386) is about upgrading to 1.11; I hear there's little progress.  [T169385](https://phabricator.wikimedia.org/T169385) is where folks have been dealing with the fallout from [upgrading to jQuery 3](https://phabricator.wikimedia.org/T124742), some of which includes issues like this that would be resolved if jquery.ui was upgraded as well. 
 See also [this comment about upgrading](https://phabricator.wikimedia.org/T49145#3838666), which notes the above.

**Comment by Amorymeltzer** [comment]
Just noting that [T71386](https://phabricator.wikimedia.org/T71386) is now (appropriately) open but not going anywhere, so, indeed, #414/[T49145](https://phabricator.wikimedia.org/T49145) is likely to be the way out.
