### ISSUE TITLE
Support Timeless skin

### ISSUE THREAD

**Issue by atlight** [azatoth/twinkle#401]
Unfortunately Twinkle requires a non-negligible amount of skin-specific logic to add its stuff to the UI (it's in twinkle.js). This means when a new skin comes out, we need to add special cases for it.

See https://phabricator.wikimedia.org/T181206 for some discussion related to this. For the time being we could simply treat Timeless like Monobook and add a set of links to the page actions portlet (`p-pagetools` in Timeless, `p-cactions` in Monobook). Eventually we should figure out how to implement a menu, as we did for Vector.

**Comment by evad37** [comment]
This has actually been fixed in Timeless: https://phabricator.wikimedia.org/T181362

**Comment by siddharthvp** [comment]
This can be closed now. Twinkle adds its menu options in Timeless in `p-cactions` which is a long menu in the right sidebar if viewport is wide enough, or a dropdown menu if not. This is much better and usable than the tabs of monobook and modern (before #721). There's no need to create a separate Twinkle menu.

**Comment by Amorymeltzer** [comment]
>the right sidebar

left

**Comment by Amorymeltzer** [comment]
I had left this open after speaking with Isarra, but agree with the above comments.

**Comment by siddharthvp** [comment]
Its on the right, at least for me. Perhaps you're confusing with cologneblue?

**Comment by Amorymeltzer** [comment]
>Perhaps you're confusing with cologneblue?

lol no.  Definitely on the left for me, so I imagine it's just a responsive/whatever thing.  13-inch screen, Chrome.

**Comment by siddharthvp** [comment]
Aha, I see. It jumps to the left when I make the window slightly smaller, and then disappears into a dropdown on making it still smaller.
