### ISSUE TITLE
Add uw-paid1 to uw-paid4

### ISSUE THREAD

**Issue by SoWhy** [azatoth/twinkle#402]
Could you please add the uw-paid warning templates to the UW module? 

TIA
SoWhy

**Comment by CmdrGaiseric** [comment]
This is an important issue.  The Foundation made declaration of paid editing an explicit part of the Terms of Use to show how seriously they take this.  A very large proportion of users we give warnings to through Twinkle are paid editors or suspected paid editors, yet Twinkle is unable to deliver this warning.

**Comment by ToBeFree** [comment]
close?
