### ISSUE TITLE
Feature Request: Improve Watchlist options

### ISSUE THREAD

**Issue by ItsPugle** [azatoth/twinkle#410]
It'd be really good if we could automate it so that an article that is added to our Watchlist because of a rollback would be automatically removed from our Watchlist after a set amount of time. 

i.e. I don't want to revert a rollback then get 10 emails a week for that one article because of edits when I'm doing 20 rollbacks a day.

**Comment by Amorymeltzer** [comment]
Neat though this would be, without a technical change I think it'd require Twinkle to save a lot of user data either locally (no thanks) or to the wiki (tons of edits).

This [feature ranked seventh](https://meta.wikimedia.org/wiki/Community_Wishlist_Survey_2019/Watchlists/Watchlist_item_expiration) on the [2019 Community Wishlist Survey](https://meta.wikimedia.org/wiki/Community_Wishlist_Survey_2019/Results), though, so it certainly seems possible in the future!
