### ISSUE TITLE
Missing welcome message: {{Template:Welcome-noteng}}

### ISSUE THREAD

**Issue by ToBeFree** [azatoth/twinkle#420]
We have a lot of translated versions of Template:Welcome-noteng, but none in Romanian. Let's add the general one for these cases, please.

**Comment by SoWhy** [comment]
@ToBeFree Actually, https://en.wikipedia.org/wiki/Template:Welcomeen-ro does exist, it is just not in the same style as the other templates. If you can fix it up to look like the other templates (i.e. with documentation and the text in both Romanian and English), it can be added to the menu. That way, both templates could be added without having to change the file twice.

**Comment by ToBeFree** [comment]
Oh, that's a good point. 

https://en.wikipedia.org/w/index.php?title=Template:Welcomeen-ro&diff=846150484&oldid=846150364&diffmode=source

😃

**Comment by ToBeFree** [comment]
Assigning this to myself, I think I can do this
