### ISSUE TITLE
Remove unneeded comments from twinklewarning.js

### ISSUE THREAD

**Issue by ToBeFree** [azatoth/twinkle#425]
"To be removed fomr (sic!) Twinkle"... well then let's do it.

https://github.com/azatoth/twinkle/blob/master/modules/twinklewarn.js#L312

https://github.com/azatoth/twinkle/blob/master/modules/twinklewarn.js#L628

https://github.com/azatoth/twinkle/blob/master/modules/twinklewarn.js#L766

https://github.com/azatoth/twinkle/blob/master/modules/twinklewarn.js#L846

**Comment by ToBeFree** [comment]
Will be fixed by #423

**Comment by ToBeFree** [comment]
Will be fixed by me (feel free to assign me) _after_ #412 is merged

**Comment by Amorymeltzer** [comment]
@ToBeFree Do you still want to open this PR?  I can do it real quick if you like.  I say remove the comments now, it's been years.

**Comment by ToBeFree** [comment]
@Amorymeltzer oh, feel free to do that, and thank you. :)
