### ISSUE TITLE
feature request: Add {{old prod full}} to talk page when PRODding article

### ISSUE THREAD

**Issue by codingatty** [azatoth/twinkle#435]
An article may be subjected to PROD only once. Ideally, when PRODding and article, an editor should place the` {{old prod full}}` template on the article's talk page. If the article survives PROD, the presence of the tag shows future editors that it has already been PRODded and is not eligible to be PRODded again. Apart from this tag (which also places the article in the category `Past proposed deletion candidates`), there's no easy way of telling whether an article has previously been PRODded.

Please add the `{{old prod full}}` template to the article's talk page when Twinkle is used to PROD the article.  Ideally, it would populate the `nom`, `nomdate` and `nomreason` parameters, but even a bald `{{old prod full}}` would be helpful. 

This feature request is complementary to the one in issue #266, but is independent of it.

**Comment by Amorymeltzer** [comment]
It's clear this is standard practice, or even that this is the correct sequence.  Asked for clarity at https://en.wikipedia.org/wiki/Wikipedia_talk:Proposed_deletion#Should_Template:Old_prod_full_be_added_with_or_after_the_prod?

**Comment by Amorymeltzer** [comment]
I think I'm in favor of this, but the [thread](https://en.wikipedia.org/wiki/Wikipedia_talk:Proposed_deletion/Archive_16#Should_Template:Old_prod_full_be_added_with_or_after_the_prod?) didn't reach consensus either way, although there was a suggestion to include a timer hiding the tag until 7 days.  Until that gets implemented or consensus is achieved one way or another, might as well close this.

**Comment by Amorymeltzer** [comment]
This was [revived, supported, and added](https://en.wikipedia.org/wiki/Template_talk:Old_prod#Template-protected_edit_request_on_16_December_2018), so this can certainly be reopened!  Much thanks to @siddharthvp.

@siddharthvp did you ever write anything up for this?  I was doing another prod thing, so I could whip something up quick if you hadn't.

**Comment by siddharthvp** [comment]
No, I only made the required on-wiki changes. Feel free to do the rest.
