### ISSUE TITLE
Add {{Empty edit request))

### ISSUE THREAD

**Issue by FlightTime1969** [azatoth/twinkle#443]
Add {{Empty edit request}} to Twinkle's Single-issue notices section.

**Comment by MusikAnimal** [comment]
We try to only add templates that are widely used, and I'm not sure {{empty edit request}} would qualify. Fortunately, you can add any custom template by going to your [Twinkle preferences](https://en.wikipedia.org/wiki/Wikipedia:Twinkle/Preferences) and changing the "Custom warning templates to display" under "Warn user". Hope this helps!
