### ISSUE TITLE
Untag support in tag module

### ISSUE THREAD

**Issue by siddharthvp** [azatoth/twinkle#473]
Alright folks, I've been working on implementing untag functionality within the tag module, the work is at [siddharthvp/untag1](https://github.com/siddharthvp/twinkle/tree/untag1). I had even created a tester-friendly version at [test.wikipedia.org/wiki/User:SD0001/friendlytag.js](https://test.wikipedia.org/wiki/User:SD0001/friendlytag.js).

Basically the (flawed) approach was to get the list of all templates present on the page using [mw:API:Templates](https://www.mediawiki.org/wiki/API:Templates), and find all the ones that are tag templates (by searching for each template in `Object.keys(Twinkle.tag.article.tags)`). Then, in a new header in the tag interface, these tags are shown pre-selected. Deselecting them and submitting removes those tags. 

The advantage of using the API to get the template list was that we needn't bother about redirects. (eg. Twinkle sees that the page has {{cleanup-PR}} even if the page is actually having {{news release}} which is a redirect to {{cleanup-PR}}) Then, to remove the template, we'll first try to find the main template. If not present, that'd mean that a redirect to the template is present. So we get the list of redirects to the template ([mw:API:Linkshere](https://www.mediawiki.org/wiki/API:Linkshere)), and go through each one till we get to the one that's on the page.

The flaw in the plan is that API:Templates lists all templates transcluded on not just the page itself, but also in the templates themselves. It goes to infinite depth. So on a page like [Water](https://en.wikipedia.org/wiki/Water), Twinkle sees the presence of {{More citations needed}} though it's not there. The page does have {{refimprove section}} in one of the sections, which is just a wrapper for {{refimprove|section=y}} and {{refimprove}} is a redirect to {{more citations needed}}. 

Ultimately, we need to come up with a better way to produce the list of tag templates present on the page, while also having an arrangement to find them for removal. ~~I was thinking something along the lines of~~

-~~Create a table containing a regex expression covering all major redirects for each tag template. As there are presently 80 templates supported, this means 80 regexes.~~

~~1st alternative:~~
- ~~Get a list of all templates on the page (just this page, single depth) using regex. Exclude any template having a |section= param, as it means these are section tags, in which we aren't interested.~~
- - ~~An interesting optimizational idea would be to consider only those templates having a |date= param, as all tags should have it. But this means Twinkle wouldn't catch the undated tags left by editors until AnomieBot has added the date. The bot takes some time, I guess around a day.~~
- ~~Test each template found on the page, with each of the 80 regexes or until a match is obtained.~~

~~2nd alternative:~~
- ~~Don't produce a list of templates. Rather, test the page text itself with each of the 80 regexes.~~
- - ~~This can be optimized by testing only the lead section. For the citation-related tags that could be under References section, and the category-related tags, we search the area starting from the References/Notes section or something like that. Note that if we choose to search the whole page text, we'd need to complicate each regex with additional logic so that section tags don't get matched.~~

~~I am leaning on the 2nd alternative.~~ But would like to hear from others on what they feel would be the most efficient method. 

UPDATE (14 Dec): see comment below.

**Comment by QEDK** [comment]
We can parse the wikitext for templates at the top of the article and identify the ones intended for header usage by matching them will all the templates present in the article maintenance tags list. Then present them as-is in the interface for removal. That's about it. This means we don't go through the issues of redirect/wrapper templates, just a handy way to remove them.

**Comment by siddharthvp** [comment]
> We can parse the wikitext for templates at the top of the article and identify the ones intended for header usage by matching them will all the templates present in the article maintenance tags list. Then present them as-is in the interface for removal. That's about it. This means we don't go through the issues of redirect/wrapper templates, just a handy way to remove them.

Hey, how'll you "identify the ones intended for header usage" ? If a page is having {{unsourced}} how'll you know that it's intended for header usage (since our tags list doesn't contain {{unsourced}}, only {{unreferenced}})? We still need to use a regex for each tag in the tags list so that the redirects are covered, right? If not clear, what I mean is that when we search for {{unreferenced}}, we actually have to search for something like `\{\{un(referenced|sourced).*?\}\}`.

**Comment by siddharthvp** [comment]
@atlight has worked on this (Issue #13, [diff](https://gist.github.com/atlight/5328823)) before. The approach is completely different - parsing the page HTML rather than wikitext. Though he doesn't seem to have any way to distinguish page tags from section tags. 

This approach can work cleanly if we get can somehow change the templates so that we can tell apart section tags from page tags just from the list of CSS classes on the html table element. The {{ambox}} metatemplate has a class parameter for setting a CSS class which if specified adds the class to the HTML element. {{Unreferenced}} presently has `| class = ambox-Unreferenced`. Just change it to `| class = ambox-Unreferenced{{#if:{{{section|}}}|-section|}}`. So that tag has class 'ambox-Unreferenced-section' if used as a section tag, or 'ambox-Unreferenced' otherwise. With this, use of wrapper templates like {{Unreferenced section}} is no longer a problem for us.

I'll need some help in editing the 80 templates to this effect, as it requires templateeditor/admin access. @Amorymeltzer ? Just quickly go on pasting (or replacing existing |class param) `| class = ambox-{{subst:PAGENAME}}{{#if:{{{section|}}}|-section|}}`. The existing class params were added to these tags by @ioeth ([1](https://en.wikipedia.org/w/index.php?title=Template:More_citations_needed&diff=prev&oldid=452031713&diffmode=source) [2](https://en.wikipedia.org/w/index.php?title=Template:Unreferenced&diff=prev&oldid=452031726&diffmode=source)) "to facilitate new Twinkle feature" (which one? a planned untag feature? afaik, those classes aren't being used anywhere in the tag module) so I guess we can make these edits without the fear of breaking any other tool, and without needing on-wiki discussion.

Once that's done, the the following approach works:
- Parse HTML using jQuery syntax to find tables elements with class ambox.
- extract the fifth class name, trim "ambox-" part, and replace underscores with spaces and see if the resulting string is a valid tag name. 
- For removal, follow the old approach as described in the original post.

**Comment by siddharthvp** [comment]
Hey those who are watching, do speak up!

From now on, it's mostly the design to be be pondered on. Since all tag templates aren't amboxes (like {{merge}}, {{in use}}), I think it'd be better, just for the sake of uniformity, to use template class names like `tag-Unreferenced` rather than `ambox-Unreferenced`. 

Also, should we modify the existing class for section tags:
`|class = tag-Unreferenced{{#if:{{{section|}}}|-section|}}` (gives class `tag-Unreferenced-section`)
or use a separate new class: 
`|class = tag-Unreferenced{{#if:{{{section|}}}| tag-section|}}` (gives classes `tag-Unreferenced tag-section`)
Which one would be a better design?

**Comment by Dinoguy1000** [comment]
The second design is better, because it adds only a single new class over the current system, and doesn't require people to potentially modify their CSS/JS to correctly select these elements (other than the suggested change from `ambox-foobar` to `tag-foobar`, of course). That being said, the suggested code isn't exactly correct; to insert a space between the class names, you need a space before the `{{`:
```|class = tag-Unreferenced {{ #if: {{{section|}}} | tag-section }}```
This is because the whitespace around the pipes in the `#if` get stripped by the parser, so the original code would result in the class name `tag-Unreferencedtag-section`.

**Comment by siddharthvp** [comment]
@Dinoguy1000 Thanks for that. In addition, I see that many templates, including {{Unreferenced}}, don't have a |section= param! Rather they have the first unnamed param {{{1}}} which if set, changes the wording from "This article" to "This {{{1}}}" producing the flexibility of producing wordings like "This section", "This table", "This section, especially so-and-so parts" etc.

We can handle this, I think, by putting class `tag-section` when {{{1}}} is specified and its value is something other than "article".

**Comment by siddharthvp** [comment]
I have thought of a third design that'd produce the cleanest implementation, at the cost of having two classes all the time. Use the class `tag-section` if it's a section tag, otherwise use `tag-article`. This is in addition to the `tag-foobar` (foobar = template name), of course. Now, in the implementation, we don't have to look for amboxes or ombxes and filter out tag-section's, just the straight jquery selector $(".tag-article") would do the job.

**Comment by siddharthvp** [comment]
Implemented in #485. None of the designs mentioned here were exactly used.
