### ISSUE TITLE
Write guidelines for contributors

### ISSUE THREAD

**Issue by Amorymeltzer** [azatoth/twinkle#477]
It would be good to have a contributing guideline.  I can throw together a draft, but I think it would be worth discussing some basics first, starting with a list of initial items to include, preferences for those items, and perhaps good examples from other repos.  I'm a little biased as a former maintainer, but I've always liked the simplicity and friendliness of [homebrew-cask](https://github.com/Homebrew/homebrew-cask/blob/master/CONTRIBUTING.md).

Some things Twinkle's `CONTRIBUTING.md` could/should include:
- How to get set up and test (fork, copy-paste in JS console, etc.)
- Style guide and recommendations (squash, eslint, etc.)
- Naming and other advice for issues/PRs (can reference a how-to-report section)
- Recommend getting consensus before significant changes

I don't know that we need a full-blown CoC, but at the very least we can commit to following enwiki's PaGs.

@azatoth @MusikAnimal @atlight @kevinji @UncleDouggie @ioeth

**Comment by siddharthvp** [comment]
Note that there is little bit of related content at the wiki: https://github.com/azatoth/twinkle/wiki
