### ISSUE TITLE
Modules can't be CSD'd

### ISSUE THREAD

**Issue by siddharthvp** [azatoth/twinkle#478]
CSD on modules fail due to the edit filter because of the  Lua error introduced. 

A similar issue is #219.

**Comment by MusikAnimal** [comment]
Do templates even work in modules?

**Comment by Amorymeltzer** [comment]
I've got a series of module-related fixes/tweaks I'm hoping to tackle in the next week once I kick this cold, mostly using the documentation instead.

**Comment by siddharthvp** [comment]
I just checked it out and see that templates don't work at all on modules. Feel free to close this.

**Comment by Dinoguy1000** [comment]
Templates do work on module documentation pages; maybe this needs a special-case (both in Twinkle and wiki policy/templates) to add CSD, etc. tags to modules' /doc subpages instead of the modules themselves.

**Comment by Amorymeltzer** [comment]
That's basically my plan.  There are some other related things I want to look into first, and it should probably be discussed, but that seems to be what's done.

**Comment by Amorymeltzer** [comment]
#515
