### ISSUE TITLE
Adding {{subst:uw-subtle}} and {{subst:uw-fringe}}

### ISSUE THREAD

**Issue by iNeedSupport** [azatoth/twinkle#484]
Hi there! I propose that the subtle vandalism and fringe template should be added to Wikipedia. The subtle vandalism would be useful if a user made edits that may look like vandalism, but at the same time they might not be vandalism at all. The fringe template would help the warned users not to give an opinion about a certain topic. The NPOV template in twinkle is too vague to show this.

**Comment by Amorymeltzer** [comment]
I think after asking twice ([1](https://en.wikipedia.org/wiki/Wikipedia_talk:Twinkle/Archive_40#Subtle_Vandalism_Template), [2](https://en.wikipedia.org/wiki/Wikipedia_talk:Twinkle/Archive_40#Proposal_of_{{subst:uw-subtle}}_and_{{subst:uw-fringe}})) it seems there isn't much appetite?  You can always add custom templates, though, that's pretty easy.  Being cognizant of #412, too.
