### ISSUE TITLE
Possible typo in code

### ISSUE THREAD

**Issue by siddharthvp** [azatoth/twinkle#486]
https://github.com/azatoth/twinkle/blob/c579c275c93cb6752a2ca7087dac068c4b6ccef5/modules/friendlytag.js#L1421

Isn't this a typo? `params.tagParameters.cleanup.trim` is of function type and the condition check would always be true.

**Comment by MusikAnimal** [comment]
Most likely a relic from when IE 8 was supported. I'm sure it can be removed.

**Comment by Amorymeltzer** [comment]
Remove in #469
