### ISSUE TITLE
{{uw-uploadfirst}} may be useful

### ISSUE THREAD

**Issue by ToBeFree** [azatoth/twinkle#489]
Today, I learned that {{uw-uploadfirst}} exists. It was one of the few cases that always made me write a custom message like "Uploading images: Hi, please see [[Wikipedia:Uploading images]]."

I think it would fit nicely into the "single-issue notices" list of the warning module.

https://en.wikipedia.org/wiki/Template:Uw-uploadfirst

**Comment by Amorymeltzer** [comment]
Per comments in #501, in particular #344

**Comment by ToBeFree** [comment]
:/

I agree with closing this, but I'd like to note that the request (and likely the others too) has been based on actual usage frequency on en.wikipedia.org. While Twinkle is maybe the wrong place to deal with the underlying issue, the problem is so frequent and hard to understand for some new users that they ignore the edit filter warning and try anyway. I believe that we may need to fix the message to explain more strongly that this will not technically work.

**Comment by Amorymeltzer** [comment]
I'd agree with that, https://en.wikipedia.org/wiki/MediaWiki:Abusefilter-warning-external-images does seem pretty ignorable — block text with nothing but bold to stand out.
