### ISSUE TITLE
Feature request: Ability to edit automatic summaries (e.g. remove auto-capitalization and period in reverting message)

### ISSUE THREAD

**Issue by Sonicwave** [azatoth/twinkle#490]
I wonder if it would be possible for users to be able to change parts of the automatic summaries when rollbacking with an explanation message. In particular, I feel that the addition of a period and the auto-capitalization of the first character makes the summary seem terse, considering that the default rollback and undo message don't include periods. I also personally think a separator of " - " between the "Reverted edits by X (talk)" and the revert reasoning looks slightly clearer than the current separator of ": ".

E.g. instead of _Reverted edits by X (talk): Test edit. (TW)_, I'm suggesting an option to edit the summary to show up as _Reverted edits by X (talk) - test edit (TW)_

**Comment by QEDK** [comment]
I'll push one for the period removal, - format however takes one more character while serving the same purpose tbh.
