### ISSUE TITLE
Cannot edit with twinkle enabled

### ISSUE THREAD

**Issue by famo** [azatoth/twinkle#495]
When I enable TW in the gadget section of the english wp, I can no longer edit articles.
Even when I try to edit my (empty) sandbox it fails.

The progress bar moves two about two third and then stops. As soon as I disable TW it works again...

Useragent:
`Mozilla/5.0 (X11; Linux x86_64; rv:64.0) Gecko/20100101 Firefox/64.0`

**Comment by Amorymeltzer** [comment]
The progress bar suggests this is with the visual editor but I (OSX, not Linux) can't replicate this regardless of skin (modern, timeless, monobook, vector), even on FF 60.  Have you installed any other scripts lately?  Does it work if you turn off the visual editor?

**Comment by famo** [comment]
Well, it happens regardless of whether I click "Edit" or "Edit source".
But even when disabling the VE - same issue.

I don't use any user scripts.

**Comment by famo** [comment]
It does work now and I cannot reproduce this issue anymore. Dunno what changed...?
Closing.
