### ISSUE TITLE
Replace "Talkback" heading by "New message"

### ISSUE THREAD

**Issue by ToBeFree** [azatoth/twinkle#513]
The "talkback" template is directed especially at new users, yet Twinkle currently adds a meaningless heading with wrong implications above it.

https://en.oxforddictionaries.com/definition/talk_back

https://www.merriam-webster.com/dictionary/back%20talk

**Comment by Amorymeltzer** [comment]
I wonder if defaulting to include your username or the date might be helpful?  I try and do that when I leave a message, but maybe it'd be too radical of a change?

**Comment by ToBeFree** [comment]
@DannyS712 thanks! 🙂 

@Amorymeltzer hmm, it does sound useful. I would use that too. However, I have no idea about the technical complexity involved.

**Comment by Amorymeltzer** [comment]
Username would be insanely easy, date only slightly less so.  I dunno, it's a lot for a default, but how often are these used daily?  It's helpful for archives, but only new users really get a lot of 'em.

**Comment by ToBeFree** [comment]
Ooooh, we can substitute magic words / parser functions.

**Comment by Amorymeltzer** [comment]
>I was wrongly assuming a need for new Twinkle code

Hmm?  You've been able to customize that heading in your preferences to say whatever you want e.g. "New Message from the exalted Jimbo" or something.

Anyway, my inclination is "New message from <insertusername>" would be a good default but I dunno how popular that would be.

**Comment by ToBeFree** [comment]
(I meant that I thought we'd need JavaScript code to insert username/date
into the heading.)
