### ISSUE TITLE
Twinkle does not place CSD template on protected pages.

### ISSUE THREAD

**Issue by RhinosF1** [azatoth/twinkle#523]
If an article is protected, twinkle will nominate it for deletion but not place a notice on the article. Should twinkle alert users first that it is protected?

Example: https://en.m.wikipedia.org/wiki/Special:MobileDiff/884872161

**Comment by Amorymeltzer** [comment]
Page protection status should be readily available to editors as `edit`/`edit this page` will change to `view source.  I suppose Twinkle could provide feedback before attempting to do any XfD tagging, but I think #176 is a much better idea that I'd like to get to in the near future.

**Comment by RhinosF1** [comment]
That seems to be an appropriate fix either that or a message first. Feel free to close as a duplicate.
