### ISSUE TITLE
Allow g14 on redirects

### ISSUE THREAD

**Issue by DannyS712** [azatoth/twinkle#530]
I just came across https://en.wikipedia.org/w/index.php?title=Dexit_(disambiguation)&redirect=no, which is a redirect to https://en.wikipedia.org/wiki/Dexit_(corporation). G14 applies, but the option isn't appearing in the CSD menu, likely because its a redirect. I haven't tagged it for deletion, so that this can be tested, but G14 should work on redirects in mainspace.

**Comment by Amorymeltzer** [comment]
G14 applies to disambiguation pages, and redirects aren't disambiguation pages.
