### ISSUE TITLE
Enable BOOKPROD in user namespace

### ISSUE THREAD

**Issue by DannyS712** [azatoth/twinkle#538]
BOOKPROD also applies to the user namespace (ns=2), but currently twinkle doesn't support tagging userspace pages with BOOKPROD.

**Comment by Amorymeltzer** [comment]
I'm wary of adding yet another tab to userspace for something so minimally used.  Perhaps we could leverage the category?  Something to think about, anyway.

**Comment by DannyS712** [comment]
@Amorymeltzer maybe include it within the XfD or CSD tabs?

**Comment by Amorymeltzer** [comment]
Opened discussion at [WT:BOOKPROD](https://en.wikipedia.org/wiki/Wikipedia_talk:Proposed_deletion_(books)#Should_Twinkle_enable_prod_in_userspace%3F)

**Comment by Amorymeltzer** [comment]
Opened #559 relying on the category to determine whether to show up in userspace or not, but I'd still like to wait for any input.
