### ISSUE TITLE
Check if AIV report was already made in /TB2 subpage

### ISSUE THREAD

**Issue by DatGuy1** [azatoth/twinkle#542]
I don't believe there should be a difference between user-reported and bot-reported in this context.

Perhaps load /TB2 subpage text at https://github.com/azatoth/twinkle/blob/430baddc3cce565f227cd7530b5faed9c968b73e/modules/twinklearv.js#L573

**Comment by Amorymeltzer** [comment]
I'm curious what other sysops think.  For me, I appreciate having both the DatBot filter reports and a user report; it suggests that the reports is somewhat more urgent and has a likelier chance of being disruptive.

**Comment by DannyS712** [comment]
Maybe warn the user that a bot has already filed a report, but give them the option to proceed anyway?

**Comment by Amorymeltzer** [comment]
🤔 That might not be a bad way to do it.  I wonder what the percent of folks who will click through would be?

**Comment by JJMC89** [comment]
I mostly ignore bot reports when I patrol AIV.
