### ISSUE TITLE
undefined "merge to" target

### ISSUE THREAD

**Issue by owcz** [azatoth/twinkle#544]
When filing a "merge to" tag, if the editor mistakenly leaves the merge target field empty, Twinkle will put the discussion at [Talk:Undefined](https://en.wikipedia.org/w/index.php?title=Talk:Undefined&action=history) (interesting talk page history). Would save a lot of headache if Twinkle would prompt the editor when that field is empty. In any case, it shouldn't start a discussion at Talk:Undefined.

Here's the log:
>Tagging article: completed (Article-whence-the-request-originated)
>Posting rationale on talk page: completed (Talk:Undefined)
>**Tagging other page (): Could not resolve redirects for:**

**Comment by Amorymeltzer** [comment]
@owcz 	I've opened #545 to deal with this, but already pushed the fix onwiki, how's it look?

**Comment by owcz** [comment]
@Amorymeltzer NICE! Yes, resolves my use case. Thanks!
