### ISSUE TITLE
XfD: Link to listing in user notification summary

### ISSUE THREAD

**Issue by DannyS712** [azatoth/twinkle#571]
Ideally, the XfD notification on user pages, which has the summary: "Notification: listing at..." would link "Listing" to the discussion itself, much like the edit summary to the page says "see ___" and has a link to the discussion.

**Comment by Amorymeltzer** [comment]
You don't think three links would be too many?

**Comment by DannyS712** [comment]
@Amorymeltzer then maybe instead of the current "Listing at __LINK__" with a link to the forum, we could use "Listing at ___" with the entire thing (including "Listing at") linking to the specific listing?
