### ISSUE TITLE
csd/xfd: Tagging a module doesn't add it to watchlist

### ISSUE THREAD

**Issue by DannyS712** [azatoth/twinkle#572]
The CSD tag is (rightly) added to the documentation page as a result of #515. However, as a result the actual module page isn't watched according to user preferences. It should be.

**Comment by Amorymeltzer** [comment]
Likewise with tfd/m, but ugh.  Gonna have to think about a smart way to do this...

**Comment by DannyS712** [comment]
I think I can do this:
After editing the /doc page successfully, call the watch api on the module
Thoughts?

**Comment by Amorymeltzer** [comment]
Sure, go for it

**Comment by DannyS712** [comment]
I'll try to get to it soon. Can you assign it to me so I remember?
