### ISSUE TITLE
Speedy: F5 incorrectly uses F9 reason

### ISSUE THREAD

**Issue by JJMC89** [azatoth/twinkle#582]
When selecting F5 from the CSD (not DI) menu, the deletion log shows `F9: Media file copyright violation without credible claim of fair use or permission` instead of `F5: Unused non-free media`.
- [Incorrect](https://en.wikipedia.org/w/index.php?title=Special%3ALog&logid=98455532)
- [Correct](https://en.wikipedia.org/w/index.php?title=Special%3ALog&logid=98457392)

**Comment by Amorymeltzer** [comment]
@JJMC89 Issue is that [[Template:Db-unfree]] was [redirected](https://en.wikipedia.org/w/index.php?title=Template:Db-unfree&diff=prev&oldid=732033544&diffmode=source) 2.5 years ago and nobody noticed?  We can update Twinkle or re-redirect the shortcut, which do you think better?

**Comment by Amorymeltzer** [comment]
Okay, should be fixed for now.  I think I'll open an RfD on db-unfree, just 'cause.  We don't need to use it, but I made [[Template:Db-orfu]] for F5 as there wasn't a db- redirect and it seemed appropriate enough given {{orfu}}.
