### ISSUE TITLE
ARV: Add link to AIV when user has already been reported

### ISSUE THREAD

**Issue by DannyS712** [azatoth/twinkle#590]
Currently, when a user has already been reported to AIV, Twinkle refuses to report them, instead saying "The comments you typed are provided below, in case you wish to manually post them under the existing report for this user at AIV:" Ideally, the text "at AIV" should link to AIV. The text shown is defined [here](https://github.com/azatoth/twinkle/blob/master/modules/twinklearv.js#L578`), but the only links that are currently shown are footer links using [morebits' addFooterLink](https://github.com/azatoth/twinkle/blob/master/morebits.js#L4134), so I don't know how to approach this.

**Comment by Amorymeltzer** [comment]
I suppose this is really asking for `Morebits.status.printUserText` to handle a span rather than just text

**Comment by DannyS712** [comment]
@Amorymeltzer if that is the best way to approach this, then yes
