### ISSUE TITLE
If a broken redirect has page history, send to WP:RfD rather than WP:G8 speedy

### ISSUE THREAD

**Issue by deryckchan** [azatoth/twinkle#591]
Copying from WT:TW / WP:DRV : 

[This deletion review](https://en.wikipedia.org/wiki/Wikipedia:Deletion_review/Log/2019_April_16#Coix_lacryma-jobi_var._ma-yuen) essentially arose from the current implementation of Twinkle which is a bit trigger-happy.

A month ago, someone forked an article, and various editors retargeted subtopic redirects, which used to point to the parent article, to the new article. Then it was discovered that the article creator was a sock, so the new article was deleted per WP:G5.

Then Twinkle comes in. The redirects that pointed to the new (and now deleted) article were batch-nominated for WP:G8. They were deleted. This process ended up creating an estimated several hundred redlinks. A better resolution of the issue could've been that, instead of WP:G8, all those redirects should have reverted to their former target.

Here's my feature request for Twinkle: when Twinkle comes across a redirect to a non-existent page, check the page history to see if the redirect had ever pointed to another page that still exists, or had been an article in the past. If it had, then recommend sending to RfD rather than speedying. Will that work?

**Comment by Amorymeltzer** [comment]
Copying my comment from there (some light editing):

> [H]aving read everything, does not the issue stem from people not properly checking before tagging or deleting broken redirects?  In particular,
>> Twinkle doesn't check page history when it nominates redirects for WP:G8 deletion, and any mistakes it makes...

> is really the fault of the taggers in question, no?  I agree that there's a real issue where useful redirects with prior or other targets get deleted when the current target is deleted, but again, isn't that on the deleting sysop for not doing their due diligence before deleting?  Deleting redirects can be turned off in [[WP:TW/PREF|Twinkle's preferences]] or unchecked when using the form.

>As to your suggestion, that'd be pretty unwieldy I think.  Checking an unknown number of prior revisions of each redirect for a page that may or may not exist would be a lot of additional API calls, potentially exponentially so, and could take quite some time to process.  There is some work at the moment by User:SD0001 regarding batch-deletion of subpages that could be relevant.  Basically, it would show a list of subpages to be deleted before being clicked.  I suppose one option would be to, rather than the above, do a system like that for redirects.  I think we'd have to see a strong consensus before doing that, though, since it takes up a lot of space and this is a popular feature.
