### ISSUE TITLE
Avoid using the client clock for anything

### ISSUE THREAD

**Issue by Amalthea** [azatoth/twinkle#6]
Twinkle uses the client clock for numerous tasks: section headers in user warnings and list pages for various XfD tasks come to mind.
Since client clocks are often a bit off (this comes up regularly), it would be beneficial to ask the server for the time, and use that one.

**Comment by DannyS712** [comment]
What about, at least of section headers and adding the time _to a page_, using substituted time parser functions? See https://en.wikipedia.org/wiki/Help:Magic_words#Other_variables_by_type

**Comment by siddharthvp** [comment]
[Relevant SO discussion ](https://stackoverflow.com/questions/38023193/javascript-date-now-consistency-across-machines-time-zones)

**Comment by siddharthvp** [comment]
> What about, at least of section headers and adding the time _to a page_, using substituted time parser functions? See https://en.wikipedia.org/wiki/Help:Magic_words#Other_variables_by_type

In all the places where we need to add time to a page (CSD/PROD userspace logging and user talk page warning), we also need to check whether the section header of the current month is already there, so we must have the time beforehand.

**Comment by siddharthvp** [comment]
> When you request a page for later editing from the api, you already get the starttimestamp in UTC. Can't that be reused ?

Indeed. Opened a PR for reusing this wherever possible.
