### ISSUE TITLE
Bug: Block should check current status

### ISSUE THREAD

**Issue by DannyS712** [azatoth/twinkle#602]
Per [report on enwiki](https://en.wikipedia.org/w/index.php?title=Wikipedia_talk:Twinkle&oldid=894002123#Block):

> Block tab still blocks if someone else blocked after the interface pops up; ideally it checks again if a block is in place before actually proceeding. -- Lofty abyss 23:49, 24 April 2019 (UTC)

**Comment by Amorymeltzer** [comment]
I've got this (mostly?) written up, but want to wait for #814
