### ISSUE TITLE
Block posting to [[WP:PNT]] on ineligible articles aka drafts

### ISSUE THREAD

**Issue by RhinosF1** [azatoth/twinkle#604]
Remove the ability to post to WP:PNT when tagging as not English per https://en.wikipedia.org/wiki/User_talk:RhinosF1#WP:PNT when on pages that shouldn't be added to PNT

**Comment by DannyS712** [comment]
@Amorymeltzer the "easiest" way I see is to do what we used to do with the CSD criteria, by separating the article and draft tags into 2 different lists. But, since this is the only difference (so far), is there a better way?

**Comment by siddharthvp** [comment]
Just add the subgroup for {{not English}}/{{rough translation}} only if
we're in mainspace. This is in function makeCheckBox.

**Comment by DannyS712** [comment]
That makes a lot of sense - nevermind. I've written a patch.

**Comment by RhinosF1** [comment]
@DannyS712 @siddharthvp - Thanks!
