### ISSUE TITLE
Open PRs to implement before #500 [tracking]

### ISSUE THREAD

**Issue by Amorymeltzer** [azatoth/twinkle#611]
💯

**Comment by Amorymeltzer** [comment]
Closing in favor of a [dedicated milestone](https://github.com/azatoth/twinkle/milestone/3)

**Comment by Amorymeltzer** [comment]
@siddharthvp Are you working on anything significant at the moment?  I'm gonna go ahead and implement #500 (with maybe a week's review/notice?) after deploying on-wiki in a few days (and dealing with any subsequent bugs), but wanted to touch base so as not to disturb any not-yet-finished work of yours.

**Comment by siddharthvp** [comment]
Nope. Go ahead.
