### ISSUE TITLE
Batch undelete mostly unsuccessful for large numbers of undeletions

### ISSUE THREAD

**Issue by MER-C** [azatoth/twinkle#613]
It took me over 10 attempts to undelete the complete list of pages at https://en.wikipedia.org/w/index.php?title=User:MER-C/Sandbox&oldid=894909090 using the batch deletion tool. The failed undeletions gave the following error:

```Undeleting page Portal:Atlas/Maps/Historical/5: [XMilCwpAEMIAAJoUaqEAAABW] Caught exception of type Wikimedia\Rdbms\DBQueryError```

While this is a server-side performance issue, it can be mitigated by adding a little delay between the undeletions.

**Comment by Amorymeltzer** [comment]
Also reported at [[[Special:Permalink/894839829#Batch undelete problem]]](https://en.wikipedia.org/wiki/Special:Permalink/894839829#Batch_undelete_problem)

**Comment by Amorymeltzer** [comment]
I haven't had a ton of availability lately, but I'm looking into this.  I did a little rewrite of some stuff, which seems to help a bit, but not entirely.  One option could be to up `maxretries` but I think it may need work on the db end.

**Comment by Amorymeltzer** [comment]
The changes in #616 are now live, and should alleviate much of this, so I'm going to close it.  I believe the underlying issue is at the database level, but until that's resolved this should hopefully suffice.
