### ISSUE TITLE
Sorting into XFD category during the deletion request process doesn't work

### ISSUE THREAD

**Issue by tyw7** [azatoth/twinkle#617]
When I select a category for an article to be placed in deletion sorting e.g. media doesn't work and the page gets sorted into u category.

**Comment by Amorymeltzer** [comment]
Go figure!  I think it's a simple fix, but I'm trying to run down when it started happening...

**Comment by tyw7** [comment]
I notice this behavior about a month ago, I think.

**Comment by Amorymeltzer** [comment]
@tyw7 Yup, I found it — it was me!  Pr incoming...

**Comment by Amorymeltzer** [comment]
@tyw7 I just pushed a quikfix on-wiki; it should take a few minutes to get through, but let me know if it works (or if I broke the whole thing!)

**Comment by tyw7** [comment]
@Amorymeltzer  Is there a test page to try it out?

**Comment by Amorymeltzer** [comment]
Testwiki, but looking at [today's log](https://en.wikipedia.org/wiki/Wikipedia:Articles_for_deletion/Log/2019_May_4), the three AfDs created more than 10 minutes after I pushed the change ([1](https://en.wikipedia.org/wiki/Wikipedia:Articles_for_deletion/Two_Headed_Alligator) [2](https://en.wikipedia.org/wiki/Wikipedia:Articles_for_deletion/The_Place_Names_of_Upper_Deeside) [3](https://en.wikipedia.org/wiki/Wikipedia:Articles_for_deletion/List_of_Turkish_volleyball_transfers_2008%E2%80%9309)) all used Twinkle and all have a category from the start, so it looks good.
