### ISSUE TITLE
Tag: Create collapsible subgroups

### ISSUE THREAD

**Issue by DannyS712** [azatoth/twinkle#621]
Background: there are way too many tag options, making it hard to find the one you are looking for. Many are already grouped with subheadings, but the groups should be collapsible

Request:
Create collapsible subgroups. Given that tag relies on checkboxes (not radio buttons), it is always possible to select multiple options. If a heading is selected, only then should the templates nested under that heading be visible to select. Selecting just the heading should not add any tags, and can either warn the user or do nothing.

Examples:
In the article tags, a "Lede" subgroup would contain:

- Lede missing
- Lede rewrite
- Lede too long
- Lede too short

all _within_ the current "Structure, formatting, and lead section" group. On the other hand, the "merge" subgroup would be the entirety of the current "Merging" section.

Another example:
Within the file tags, a "bad format" subgroup would contain

- Bad format
- Bad GIF
- Bad JPEG

while a "keep local" group would contain

- {{Do not move to Commons}} (PD issue)
- {{Do not move to Commons}} (other reason)
- {{Keep local}}

I hope this explanation makes sense.

**Comment by siddharthvp** [comment]
That would make for a pathetic user interface. It would be better to implement some sort of search tool within the tag interface.

**Comment by Amorymeltzer** [comment]
Agree that #647 would be a better and cleaner way to handle clutter.
