### ISSUE TITLE
{{R from alternative language}} tag broken

### ISSUE THREAD

**Issue by jengel-rit** [azatoth/twinkle#624]
Currently, when I try to add {{R from alternative language}} tags to redirects Twinkle silently fails. It doesn't appear to matter whether I enter language codes or fill in other parameters. I am still able to use other tags, even after attempting to add the {{R from alternative language tag}}

System specs: Mac OS 10.14.4, bug is present on  the latest versions of Safari and Firefox.

**Comment by Amorymeltzer** [comment]
Issue is popping up at https://github.com/azatoth/twinkle/blob/master/modules/friendlytag.js#L1546, seems to be that items in the file and redirect tags only have the `name` as `fileTags` or `redirectTags`, without their appropriate suffix.  cc @siddharthvp

**Comment by Amorymeltzer** [comment]
Ah okay had a quick moment, the issue is the `div` item there, the `$(form).find("[name^='" + name_prefix + "']").each(function(idx,el) {` gets unhappy with it.

**Comment by Amorymeltzer** [comment]
Thanks for the report @jengel-rit!  #625 should fix things.  I was planning on doing a big update on-wiki tomorrow morning/afternoon, so I'll take care of it then.  It's not a great idea to merge code quickly and right before bed! 😴

**Comment by Amorymeltzer** [comment]
This is now merged and live, should be good to go!
