### ISSUE TITLE
Unable to see rollback links on diff pages

### ISSUE THREAD

**Issue by Gazoth** [azatoth/twinkle#627]
Rollback links are not displaying on diff pages since the last update. I could see the links till around 16:00 UTC on 8 May, but I've not been able to see them since then. I've tried disabling all beta features, all custom JS scripts, all other gadgets except Twinkle, switching to a different browser, disabling all add-ons, but none of it made a difference. Explicitly adding showRollbackLinks pref in twinkleoptions.js also didn't help. Twinkle itself is loading, as I'm able to see "[welcome]" button for new users on the diff page. The rollback options show up just fine on contributions page, the issue is visible only on the diff page.

I don't know if the browser version will make a difference, but I can see the issue on both Chrome 74.0.3729.131 and Firefox 66.0.4.

**Comment by Amorymeltzer** [comment]
@Gazoth Can you paste an example diff link where the agf/rollback/vandal links don't show up but should?  They show up fine for me.

**Comment by Gazoth** [comment]
[Here is an example](https://en.wikipedia.org/w/index.php?title=BrahMos&diff=896161533&oldid=896158762&diffmode=source). I can see the welcome link as the editor of this revision is new, but I cannot see the rollback links. Also, I can see "restore this revision" link on oldid pages.

**Comment by Amorymeltzer** [comment]
@Gazoth That diff doesn't include the latest revision of the page; the agf/roll/vandal links  only show up when you're looking at the latest revision on the right-hand side of the two-column diff.  Try [this link](https://en.wikipedia.org/w/index.php?title=BrahMos&diff=prev&oldid=896346291).

**Comment by Gazoth** [comment]
I can see the issue in the link that you provided too. Even if the revision is not the newest, I should have been able to see "restore this revision" link, but I'm unable to see that too.

**Comment by Amorymeltzer** [comment]
Okay then, can you copy the url of the latest diff of the article Macbeth and paste it here?  That might help.  Are you using the visual editor?

Additionally, when you have a moment, can you get a few pieces of information for me from [your preferences](https://en.wikipedia.org/wiki/Special:Preferences)?  It might help me replicate your issue.
- From the Appearance tab: your skin, and which boxes under **Diffs** you have checked
- From the Editing tab: whether you have the toolbar or "disable visual editor" boxes checked
- From the Gadgets tab: all boxes you have checked
- From the Beta tab: all boxes you have checked

**Comment by Gazoth** [comment]
I found the issue. I had enabled "Do not show page content below diffs" under Preferences > Appearance > Diffs. Disabling that option brings back the rollback links.

[Here is the latest diff from Macbeth](https://en.wikipedia.org/w/index.php?title=Macbeth&diff=893580958&oldid=893579920&diffmode=source). I'm not using the visual editor, but I do have the visual differences beta enabled. I don't think the rest of the questions are relevant anymore, but I can still answer them if enabling "Do not show page content below diffs" does not reproduce the issue for you.

**Comment by Amorymeltzer** [comment]
Ah, okay, I've got it!  It's from #562, specifically https://github.com/azatoth/twinkle/pull/562/files#diff-1dcb5e0e39547eb0cb4124afd50081bfR83.  Basically, that option sets `wgRevisionId` to 0, so the check that the content displayed is the same as the diff given fails.  I'll have to do some testing tomorrow, but I think that check might be overly parsimonious.

**Comment by Amorymeltzer** [comment]
@Gazoth Should be working now, let me know how it looks!

**Comment by Gazoth** [comment]
Working fine with no issues.  Thanks for the quick response!
