### ISSUE TITLE
Search user warnings

### ISSUE THREAD

**Issue by RhinosF1** [azatoth/twinkle#631]
This probably a big one but it would be nice to have the ability to search the user warning dialog to find which warning you are looking for easier

**Comment by siddharthvp** [comment]
This is basically asking for [jquery.chosen](https://harvesthq.github.io/chosen/) again. Expect a PR soon.

**Comment by RhinosF1** [comment]
@siddharthvp - That looks good.

A few questions:
1. Will that serach all submenu's?
2. Will it include searching bu description and template name

**Comment by Amorymeltzer** [comment]
@siddharthvp As you [predicted](https://github.com/azatoth/twinkle/pull/580#issuecomment-486540025)!  Before you get to in-depth on this, would it help or hurt if I merged #592?

**Comment by siddharthvp** [comment]
> A few questions:
> 
> 1. Will that serach all submenu's?
> 2. Will it include searching bu description and template name

1. no
2. yes

**Comment by siddharthvp** [comment]
@Amorymeltzer Go ahead with that. 

> Before you get too in-depth on this

Unless I'm much mistaken, this won't take more than 3-4 lines of extra code. Feel free to do it yourself if you wish.

**Comment by RhinosF1** [comment]
Thanks for the reply. Ideally it should search warnings across every subsection not just that menu your own (like 4im)

**Comment by Amorymeltzer** [comment]
@siddharthvp 
>Go ahead with that
I'm fine waiting for more input, just wanted to make sure it wouldn't muck up how `chosen` traverses the items.
