### ISSUE TITLE
XfD: Allow notifying page creator for CfD/S

### ISSUE THREAD

**Issue by DannyS712** [azatoth/twinkle#638]
Not sure what, but out of all of the options in XfD, Categories for speedy renaming is the only one that doesn't allow notifying creators. It should.

**Comment by siddharthvp** [comment]
The CfD/S process, much like RM/TR or RM, does not require notifications. There isn't even a template for that.

**Comment by Amorymeltzer** [comment]
No notification templates = no notifications
