### ISSUE TITLE
tag: Custom tags unchecked when changing view (thus ignored statusNode)

### ISSUE THREAD

**Issue by Amorymeltzer** [azatoth/twinkle#652]
Two phenotypes related to the same issue, but when changing between alphabetical and category listing of tags, any custom checked tags are unchecked.  This is a bug in the current version on enWiki.

Relatedly, that unchecking isn't detected by the `statusNode` from #648, so since the count update is all relative, changing the category will make permanent an off-by-n error.

I can look into this tomorrow/Monday when I have time, but cc @siddharthvp in case you've got a moment

**Comment by siddharthvp** [comment]
radical idea: do we really need the alphabetical viewing mode? It's a pain in the ass when it comes to maintenance or writing new features.

**Comment by siddharthvp** [comment]
I'd imagine custom tags to be not so used. There's a significant bug with custom tags in the current wiki version. They always get grouped into {{multiple issues}} when {{multiple issues}} is being added to the article(!), though we know nothing about whether MI supports them. Don't worry I've fixed it as part of #485, though.

**Comment by Amorymeltzer** [comment]
Said this in #653, but this dates back five years ago to b28bc422.

>do we really need the alphabetical viewing mode

The filter from #647 likely negates the need for it down the line, but it's being used, including by some notably-active mainspace editors/taggers.  Maybe wait and see for 6-12 months, then reassess on-wiki.
