### ISSUE TITLE
twinklewarn: single-issue notices: Wrong <label for="node_11">

### ISSUE THREAD

**Issue by ToBeFree** [azatoth/twinkle#659]
While "Optional username that was reported (without User:)" is correct for "uw-aiv", that's pretty much the only warning message that requires such a label. All others should use "Linked page".

![twinkle-wrongtext-20190606](https://user-images.githubusercontent.com/1029811/59039017-4ebb6a80-8874-11e9-836e-b891ca3caa54.png)

**Comment by Amorymeltzer** [comment]
Presumably related to how we change that text for a few select templates :https://github.com/azatoth/twinkle/blob/1ca0527ae3c4bd9939df1e714a68ad244b4b72de/modules/twinklewarn.js#L1172-L1191 (see also #432).

**Comment by Amorymeltzer** [comment]
Changing
```javascript
$('select[name=sub_group]').chosen({width: '100%', search_contains: true});
```
to
```javascript
$('select[name=sub_group]').chosen({width: '100%', search_contains: true}).on('change', function(e) {
                Twinkle.warn.callback.change_subcategory(e);
        });
```

Should do it?

**Comment by Amorymeltzer** [comment]
Hmm, do we even need the original event if we have to do this?  I don't think so
