### ISSUE TITLE
Page edits fail on mass message lists

### ISSUE THREAD

**Issue by DannyS712** [azatoth/twinkle#680]
I cannot use CSD, XfD, or RfPP (tag) on https://en.wikipedia.org/wiki/User:DannyS712/San_Diego_Meetup, which I wanted deleted. Rather than manually tagging it, I'm leaving it up so that I can test when this is patched. The error received is: `Tagging page: Failed to save edit: Invalid content data`

**Comment by Amorymeltzer** [comment]
#251

**Comment by DannyS712** [comment]
Tracked on phabricator: https://phabricator.wikimedia.org/T226929

**Comment by siddharthvp** [comment]
> Tracked on phabricator: https://phabricator.wikimedia.org/T226929

@DannyS712 wow, now you are a mediawiki hacker!

**Comment by DannyS712** [comment]
> > Tracked on phabricator: https://phabricator.wikimedia.org/T226929
> 
> @DannyS712 wow, now you are a mediawiki hacker!

Only once the patch is merged - still hasn't been reviewed, despite having tests to demonstrate that it works and a +2 verified

**Comment by DannyS712** [comment]
@Amorymeltzer why is this closed?

**Comment by Amorymeltzer** [comment]
As noted in #251, I think it's better to deal with non-standard content models in a more concerted fashion, especially given stuff like #603 can get out of hand quickly.  Maybe I misread, but is there anything proposed to be done here?  I thought you were taking care of it upstream?

**Comment by DannyS712** [comment]
Upstream I was adding the ability to edit the description via the API. Once that ability is added, and once https://phabricator.wikimedia.org/T231401 allows retrieving the current description, twinkle (likely morebits) will still need to be updated to actually use the new API feature to tag pages
