### ISSUE TITLE
R from draft

### ISSUE THREAD

**Issue by CptViraj** [azatoth/twinkle#683]
Add **{{R from draft}}**

**Comment by Amorymeltzer** [comment]
I'm not sure there'd be a lot to gain from adding this: it doesn't seem to be used that frequently, and we've got a pretty unwieldy list for redirects already.

**Comment by siddharthvp** [comment]
Agreed. This one seems particularly pointless. There are thousands and thousands of redirects from draft to mainspace, and there doesn't seem to be any benefit in tagging them.
