### ISSUE TITLE
Twinkle CSD G11 does not work on testwiki

### ISSUE THREAD

**Issue by TheSandDoctor** [azatoth/twinkle#689]
![testwiki_twinkle](https://user-images.githubusercontent.com/33101968/63228022-11435980-c1a2-11e9-8e0f-71f435a46054.PNG)
It appears that deleting a page as G11 using Twinkle on test-wiki does not work, merely generating the below error:

Building deletion summary: Unable to generate summary from deletion template
Asking for reason: you didn't give one. I don't know... what with admins and their apathetic antics... I give up...

_This was initially [created on phabricator](https://phabricator.wikimedia.org/T230697) prior to revi linking me here._

**Comment by JJMC89** [comment]
{{[db-g11](https://test.wikipedia.org/wiki/Template:Db-g11)}} didn't exist on testwiki. It should work now that I've created it.

**Comment by Amorymeltzer** [comment]
Indeed — the template is used to build the summary, so if the template doesn't exist...
