### ISSUE TITLE
BUG> Wikipedia:Miscellany for deletion nominations

### ISSUE THREAD

**Issue by MattLongCT** [azatoth/twinkle#691]
Examples: [Wikipedia:Miscellany for deletion/Draft:Yash](https://en.wikipedia.org/wiki/Wikipedia:Miscellany_for_deletion/Draft:Yash), [Wikipedia:Miscellany for deletion/Portal:Islam in China](https://en.wikipedia.org/wiki/Wikipedia:Miscellany_for_deletion/Portal:Islam_in_China), and [Wikipedia:Miscellany for deletion/Portal:Microsoft (2nd nomination)](https://en.wikipedia.org/wiki/Wikipedia:Miscellany_for_deletion/Portal:Microsoft_(2nd_nomination))

When creating a nomination page it uses {{[la](https://en.wikipedia.org/wiki/Template:La)}} when it really should be using {{[Pagelinks](https://en.wikipedia.org/wiki/Template:Pagelinks)}} or {{[Ln](https://en.wikipedia.org/wiki/Template:La)}}.

This bug is recent, and I don't really get why it was changed from {{Pagelinks}} when it so obviously broke things, but ¯\_(ツ)_/¯

**Comment by JJMC89** [comment]
It was caused by [this edit](https://en.wikipedia.org/w/index.php?diff=912975748) to `{{mfd2}}`. I've fixed it with [this edit](https://en.wikipedia.org/w/index.php?diff=913134679).
