### ISSUE TITLE
Update API error handling for impending breaking changes

### ISSUE THREAD

**Issue by atlight** [azatoth/twinkle#704]
There's an [upcoming breaking change to the MediaWiki API](https://lists.wikimedia.org/pipermail/mediawiki-api-announce/2019-September/000148.html) which will impact our ability to display relevant error messages to users in the case of an abuse filter being triggered or the spam blacklist being hit.

We'll need to update [twinklefluff](https://github.com/azatoth/twinkle/blob/afcd932dd983d9f486f3f0457620abdfb6844479/modules/twinklefluff.js#L493) and [morebits](https://github.com/azatoth/twinkle/blob/28d50ac8b20fd474c00b29589360a08f0066189f/morebits.js#L2590) to reflect this breaking change.

**Comment by Amorymeltzer** [comment]
Thanks for opening the issue @atlight — I saw the email while on the playground yesterday, I'll try and get around to it in the next few days.  The hardest part, I imagine, would be testing it.
