### ISSUE TITLE
tag: edit summaries are broken

### ISSUE THREAD

**Issue by siddharthvp** [azatoth/twinkle#718]
Since #485, edit summaries generally are grammatically wrong, wherever {{multiple issues}} is being added. [Example edit](https://en.wikipedia.org/w/index.php?title=Army_Service_Component_Command&diff=prev&oldid=918863852). Curiously, in [this edit](https://en.wikipedia.org/w/index.php?title=Christopher_Appleton&diff=prev&oldid=918864777), "tag" is singular whereas in the the former edit, plural "tags" is used, though in both cases only 1 tag was added. Also, the "tag" word after "(within {{multiple issues}})" shouldn't really be there.

I made some efforts to ensure correct edit summaries in the initial few iterations of 485, but later lots of changes were made and I neglected to check up on the correctness of edit summaries.

As the codes for producing the edit summaries are quite involved and spread across multiple places, I propose simplifying them to remove mention of "(within {{multiple issues}})". I think that is a detail that isn't important enough to be in the edit summary, and this would simplify a lot of edit summary generation code.

**Comment by Amorymeltzer** [comment]
I'm not sure I particularly care whether MI is called out in the edit summary, do taggers?

**Comment by DannyS712** [comment]
I can action the removal of the multiple issues tag - if there are no objections, @Amorymeltzer can you assign this to me?

**Comment by QEDK** [comment]
@DannyS712 Are you still working on this?

**Comment by DannyS712** [comment]
Completely forgot, sorry. Do you want to take a stab?

**Comment by Amorymeltzer** [comment]
Just removing MI, yeah?  If you've no interest @QEDK I can.

**Comment by QEDK** [comment]
@Amorymeltzer I doubt I will be getting to this before 16th since I'm going back to my parents' (coronavirus gave us extra vacay, make of that what you will). If you want to resolve this before then, why not? :)
