### ISSUE TITLE
How to disable hardware acceleration?

### ISSUE THREAD

**Issue by evandrocoan** [azatoth/twinkle#730]
Twindle just crashed my Linux:
```
Oct 18 14:26:37 evandro-pc kernel: [309258.854944] [drm] GPU HANG: ecode 9:0:0x89b0929b, in twinkle [12478], reason: Hang on rcs0, action: reset
Oct 18 14:26:37 evandro-pc kernel: [309258.854956] i915 0000:00:02.0: Resetting rcs0 after gpu hang
Oct 18 14:26:38 evandro-pc kernel: [309260.071284] [drm:gen8_reset_engines [i915]] *ERROR* rcs0: reset request timeout
Oct 18 14:26:38 evandro-pc kernel: [309260.071330] i915 0000:00:02.0: Resetting chip after gpu hang
Oct 18 14:26:39 evandro-pc kernel: [309261.286980] [drm:gen8_reset_engines [i915]] *ERROR* rcs0: reset request timeout
Oct 18 14:26:39 evandro-pc kernel: [309261.287024] [drm:i915_reset [i915]] *ERROR* Failed to reset chip: -5
Oct 18 14:26:40 evandro-pc xdg-desktop-por[22547]: xdg-desktop-portal-gtk: Fatal IO error 11 (Resource temporarily unavailable) on X server :0.0.
```

This is a bug in my Intel CPU Hardware acceleration (GPU). The fix for it is either throw my CPU away or disable hardware acceleration in all my applications.
1. https://bugs.freedesktop.org/show_bug.cgi?id=104522
1. https://bugs.freedesktop.org/show_bug.cgi?id=104520
1. https://bbs.archlinux.org/viewtopic.php?id=232551
1. https://forum.manjaro.org/t/i915-gpu-hang-solved/37200
1. https://bugs.freedesktop.org/show_bug.cgi?id=108614

Usually, I can do that by passing a command-line argument as `--disable-gpu`. How could I disable Hardware Acceleration on Twinkle?

**Comment by martijnhoekstra** [comment]
Definitely the wrong project: This is the Twinkle javascript library/userscript for Wikipedia.  Maybe you're looking for https://github.com/LubosD/twinkle ?

**Comment by evandrocoan** [comment]
Yes! Thanks for pointing out.
