### ISSUE TITLE
Don't show "unlink" on non-deleted pages

### ISSUE THREAD

**Issue by siddharthvp** [azatoth/twinkle#742]
There is no reason why a page that exists should be unlinked (or is there?). As unlinking only happens after a page is deleted, I propose that the "unlink" tab be shown only on non-existing pages. 

While the main motive is uncluttering the twinkle menu, it also prevents mistakes from inexperienced users like [this](https://en.wikipedia.org/w/index.php?title=Special:Contributions&offset=20191011171559&limit=10&target=Dmehus) (in this case, the AfD ultimately ended as keep and the edits had to be reverted manually).

**Comment by Amorymeltzer** [comment]
I'd be against this, but ymmv.  unlink has been less valuable given the excellence of XfDCloser, but that only increases the relative value of being active on non-deleted pages.

**Comment by DannyS712** [comment]
I would suggest either declining or creating an option (on by default) regarding if it should be available

**Comment by Amorymeltzer** [comment]
Yeah, those are the options.  As above, I think it's fine as-is, and I don't think a preference is worth it, too picayune.

**Comment by Amorymeltzer** [comment]
Per above: valid (if somewhat unlikely) to use, menu can be cleaned up a bit with #793
