### ISSUE TITLE
Make Morebits into a hidden gadget

### ISSUE THREAD

**Issue by evad37** [azatoth/twinkle#748]
Notifying Twinkle developers that there's a suggestion at [en:WP:IANB#Hidden gadgets](https://en.wikipedia.org/wiki/Wikipedia:Interface_administrators%27_noticeboard#Hidden_gadgets) to make Morebits into a hidden gadget.

The only changes needed would be to MediaWiki:Gadgets-definition, and to documentation.

**Comment by Amorymeltzer** [comment]
cc @MusikAnimal but I generally agree with this (and will say so there).  I can take care of it Sunday if another IA hasn't yet.

I've been thinking about how better to document the gadget definition here, so this goes well with that I suppose.
