### ISSUE TITLE
Close Menu buttons not lining up

### ISSUE THREAD

**Issue by teepee2345** [azatoth/twinkle#766]
When the Twinkle menu loads, the button to close the window is out of alignment. See attached images.

![Screen Shot 2019-11-26 at 14 24 10](https://user-images.githubusercontent.com/17791218/69665718-f31aae80-1058-11ea-8fd2-649d664ce061.png)

![Screen Shot 2019-11-26 at 14 22 42](https://user-images.githubusercontent.com/17791218/69665717-f31aae80-1058-11ea-8dbf-42b2a42d14de.png)
Pictures were taken on 26 November 2019, at 1922 and 1924 UTC

**Comment by Amorymeltzer** [comment]
Thanks for reporting this!  I noticed this behavior a few months (September?) ago (I actually thought I already opened an issue 😳) but couldn't figure out why when I looked.

**Comment by siddharthvp** [comment]
I too found this happening a few months ago; but the issue isn't there now (for me).

**Comment by Amorymeltzer** [comment]
@teepee2345 Are you still seeing this?  It seems to be gone on my end.

**Comment by teepee2345** [comment]
It looks to be gone now
