### ISSUE TITLE
Should we remove moment dependency? (arv)

### ISSUE THREAD

**Issue by Amorymeltzer** [azatoth/twinkle#769]
Added in a2c3f93a / 0beacc07 and originally loaded as a Twinkle module, it has since #249 been a simple dependency via the gadget definition.

Currently, it is used *only* for a single module, `twinklearv.js`, and even then only for single segment: reporting to WP:AN3.  In the past month, WP:AN3 has averaged about 5 reports every 3 days (i.e. there have been just under 50 reports in 31 days).  The formatting stuff is replaceable, so only the relative language from .` calendar` ("Today at 7PM") would be lost.  The specific display (see #770 for proposed implementation) isn't particularly important here, but the upshot is that momentjs is (1) barely used and (2) definitely not necessary.

I'm not sure how caches are treated on phones or tablets, but on my laptop it looks pretty generous.  Still, moment is somewhere around 8% of the full-sized Twinkle package (per inspect), and just under 10% as actually loaded (that's 86.8 and 23.4 kb, respectively).  It leads to fewer than two edits a day, so it's fairly unnecessary right now and just adds some weight and complexity.  There's probably a future for moment here as regards i18n, but it isn't now.

**Comment by Amorymeltzer** [comment]
I first mentioned this in https://github.com/azatoth/twinkle/issues/723#issuecomment-547864351 where @siddharthavp said:
>Its a cheap library loaded efficiently via the resourceloader. And it makes date handling a bliss, as well as less error-prone, and is free of browser/es-version quirks potentially associated with JS Date. We could even think of replacing all instances of JS Date and use moment exclusively.

(also cc @MusikAnimal,  who commented there)

Another option would be to use the CDN (à la #692) for `dayjs`, which is smaller, but that's probably not worth it (no resourceloader).  There has been some [discussion of removing moment](https://phabricator.wikimedia.org/T146798) in core in favor of something else like dayjs.

**Comment by siddharthvp** [comment]
> Another option would be to use the CDN (à la #692) for dayjs, which is smaller, but that's probably not worth it (no resourceloader). 

Or how about just writing a lightweight date library ourselves, customised for our needs? We could put it in Morebits, so that it can use the ResourceLoader.

**Comment by MusikAnimal** [comment]
I was under the impression that dependencies aren't "downloaded" more than once, no matter how many gadgets use them. As you say, MediaWiki Core uses moment, so if my belief is true, then we shouldn't be adding much weight in using it ourselves. Or maybe I've had this wrong all along?

**Comment by siddharthvp** [comment]
moment was recently removed from the MediaViewer. Now, according to codesearch linked on phab, moment is being used only in `mediawiki.widgets` and `mediawiki.ForeignStructuredUpload`, neither of which are loaded by default (and in mobileFrontend, which is also not loaded for desktop users). So I would guess loading moment isn't as efficient now as it used to be before June (when it was removed from MediaViewer).

**Comment by Amorymeltzer** [comment]
@MusikAnimal: That's right, but moment is not currently loaded by default.  I didn't know about @siddharthvp's answer re: MediaViewer, but I started noticing this this fall, so that would make perfect sense to me.

>Or how about just writing a lightweight date library ourselves, customised for our needs?

Although also unnecessary since we don't actually have any needs atm?

**Comment by siddharthvp** [comment]
> Although also unnecessary since we don't actually have any needs atm?

Isn't #770 basically a need? Also, a date library can be used for better ways of writing code like [this](https://github.com/azatoth/twinkle/pull/777/files#diff-b37f48b65cd39494c40fe24d76458cedR1309-R1315) and [this](https://github.com/azatoth/twinkle/pull/777/files#diff-b37f48b65cd39494c40fe24d76458cedR1336-R1338). 

I did write [Morebits.date](https://gist.github.com/siddharthvp/dcdc51e05aa79a5856e63ecc116dcacf) after I left the comment above. The main highlights are:
- it's a simple wrapper around JS Date. Not strictly a subclass, but [all native methods can be used on Morebits.date objects](https://gist.github.com/siddharthvp/dcdc51e05aa79a5856e63ecc116dcacf#file-morebits-date-js-L190).
- constructor can parse MW signature timestamp format
- `add` and `isBefore`/`isAfter` together make stuff like [this](https://github.com/azatoth/twinkle/pull/777/files#diff-b37f48b65cd39494c40fe24d76458cedR1336-R1338) easier to write: as `new Morebits.date(latest.date).add(Twinkle.getPref('autoLevelStaleDays'), 'days').isAfter(new Date())`
- the `calendar` function is a  full replication of `calendar` in `moment` (I believe), in just 20 lines of code. (I did [say earlier](https://github.com/azatoth/twinkle/issues/723#issuecomment-547864351) that `calendar` was difficult to re-implement, bah!) Can be used for #770.
- bonus: what `monthHeader `and `monthHeaderRegex` do is being used across across 4 modules - speedy, prod, warn and block. It makes sense to centralise the code here in morebits. 
- <200 lines including all the jsdocs and the large block of commented out code.

Most of this is moment-inspired. Don't know what you think about it, but I guess this would make for a fine addition to Morebits? (also ping @MusikAnimal for feedback). Many parts are probably overkill (like `format` being able to work with any timezone as well as decipher the user preferences time zone).

**Comment by Amorymeltzer** [comment]
FWIW, my point about a need was just that #770's display is really a choice.  Sure, it's a spectrum — we *need* to not show `Tue Jan 07 2020 16:20:01 GMT-0500 (Eastern Standard Time)` or `1578432013989`) but the current display was a *choice*, and #770 was made to approximate those previous results, without regard to whether it was preferable (it's a draft because I'm not sure it is).

At any rate @siddharthvp, that `Morebits.date` looks pretty damn dope! 💯  I haven't given it a full deep-dive, but I think it likely makes the answer here a resounding **Yes**! 🎉  cc @MusikAnimal (currently on vacation) but if/when you think it's ready for review, I think you should open a PR.  Mentioned at https://github.com/azatoth/twinkle/issues/723#issuecomment-571773055.

I think it's likely I won't get around to reviewing and incorporating it this month but maybe next round?  How's that sound?  I'd be inclined to just merge #770 to lighten the load in the mean time, but I guess it's not urgent.

Really great work here, truly appreciate it. 🦄
