### ISSUE TITLE
Twinkle-specific CSS in morebits.css

### ISSUE THREAD

**Issue by Amorymeltzer** [azatoth/twinkle#778]
- [x] `morebits.js` [uses `.tw_status`...](https://github.com/azatoth/twinkle/blob/18798af0c500dc93ef40f65d5f3c8edccf026e0e/morebits.js#L3721) but shouldn't this more appropriately be named `mb_status`? (#885)
- [x] 511bd8f3 (re-)added Twinkle-specific CSS (see the `portlet` section), is there a good reason that shouldn't be in `twinkle.css`? (#893)

**Comment by Amorymeltzer** [comment]
@enterprisey This was inspired by your recent WT:TW question, but I'm leaving for a few weeks so I figured I'd open this instead of looking into this further.

**Comment by siddharthvp** [comment]
The `/* Portlet */` section isn't even Twinkle-specific. It affects the whole skin. It doesn't really belong anywhere. Previously noted in https://github.com/azatoth/twinkle/pull/721#issuecomment-551935531.

**Comment by Amorymeltzer** [comment]
Opened PRs for both of the issues, as well as #892 for @enterprisey's specific request, so closing.
