### ISSUE TITLE
Talkback optout gives negative feedback

### ISSUE THREAD

**Issue by QEDK** [azatoth/twinkle#797]
If user has not opted out, we should not display an opt-out message at all. 
`if(Twinkle.talkback.optout)` should deal with this correctly but apparently is not.
@Amorymeltzer

**Comment by Amorymeltzer** [comment]
It's actually in the other check, where only `status.length` is checked, but yeah, that's on me.  #798 should do it; already live on enwiki.

**Comment by QEDK** [comment]
> It's actually in the other check, where only `status.length` is checked, but yeah, that's on me. #798 should do it; already live on enwiki.

Ahh right, was thinking which of the checks were failing, thanks for the quick fix.
