### ISSUE TITLE
config doesn't handle empty values anymore

### ISSUE THREAD

**Issue by Amorymeltzer** [azatoth/twinkle#799]
While you can still set various inputs to be empty – talkback section headings, default welcome template, prod log subpage, etc. — loading config again will lead to the default being re-inserted and replaced upon your next loading.  This means that it's possible to go to TW/PREF and just click save, and have a difference saved.

I presume this comes after #762 (cc @siddharthvp) but haven't looked into it yet.

**Comment by siddharthvp** [comment]
Gosh! What a noob mistake! Thanks for finding the bug. PR filed.
