### ISSUE TITLE
Space for portlet added without portlet

### ISSUE THREAD

**Issue by DannyS712** [azatoth/twinkle#809]
As a non-admin
When I visit https://en.wikipedia.org/wiki/Special:PrefixIndex/User:DannyS712
I should not see the space for the twinkle portlet
Because no portlet is ever added
Because non admins have no functions accessible on special:prefixindex

**Comment by DannyS712** [comment]
`.client-js > body.skin-vector.mw-special-Prefixindex #p-cactions` only makes sense for admins, but the css page (twinkle-pagestyles.css) is shared.

Applying `$('#p-cactions').css('margin-right', 'initial')` removes the space

I don't see an elegant way to check if any portlets have been added, since they all have unknown ids and classes. I see 2 options

* Create a `Twinkle.hasPortlets` that is set to true with any calls to `addPortletLink` during startup. Check if its true, and if not, revert the css. Either way, delete it
* Specifically say that on Special:PrefixIndex, if the user is a non-admin, apply the css revert

**Comment by siddharthvp** [comment]
> I don't see an elegant way to check if any portlets have been added

You can do that simply by checking `$('#p-twinkle').length`, after all modules have been initialised. 

> Applying $('#p-cactions').css('margin-right', 'initial') removes the space

Nice idea! It's worth noting that wouldn't conflict (untested) with [MoreMenu spaces](https://en.wikipedia.org/wiki/MediaWiki:Gadget-dropdown-menus-pagestyles.css) as those are reserved in an entirely different way.

**Comment by Amorymeltzer** [comment]
I'm on mobile so can't check for a while (👶😫) but is this visually apparent or just in the console?

Another thought would be to change the Twinkle special page check to only include a few if user==sysop.

**Comment by DannyS712** [comment]
> I'm on mobile so can't check for a while (👶😫) but is this visually apparent or just in the console?
> 
> Another thought would be to change the Twinkle special page check to only include a few if user==sysop. Something like
> 
> ```js
> var specialPageWhitelist = [ 'Block', 'Contributions'];
> if (userIsSysop) {
> 	specialPageWhitelist.push('DeletedContributions', 'Prefixindex');
> }
> ```
> 
> Then quit (and remove?) if it fails the later check.
> 
> (Special:block has warn, etc.)

The check cannot, however, be applied to the CSS, and we don't want to call this on every page (even those where the css isn't applied) in case it conflicts with other scripts...

**Comment by siddharthvp** [comment]
@DannyS712 are you going to open a PR? 

This should be resolved before #793 is merged/deployed, because the ability to turn off certain modules only compounds the issue.
