### ISSUE TITLE
Warn: Overflow triggered by opening options - stacking

### ISSUE THREAD

**Issue by DannyS712** [azatoth/twinkle#810]
Steps to reproduce:
Visit https://en.wikipedia.org/wiki/User:DannyS712
Activate the warn module
Note that the overall morebits window doesn't overflow
Open the dropdown list of templates, and close it
Note that the overall morebits window now overflows and has a scrollbar, with extra blank space below the "Choosing a warning level • Twinkle help" footer

I suspect this is caused by the template dropdown being a part of the morebits window (i.e. opens "behind" the front of the frame, and the bottom is cut off), unlike, other dropdowns that open in front of the frame.

**Comment by DannyS712** [comment]
Also, when scrolling down, the header "Twinkle * Warn/notify user" moves with the scrolling, it probably shouldn't

**Comment by siddharthvp** [comment]
To be resolved by #692.

**Comment by Amorymeltzer** [comment]
This is, essentially, #665, no?
