### ISSUE TITLE
Warn if reporting a blocked user to AIV/UAA

### ISSUE THREAD

**Issue by creffett** [azatoth/twinkle#816]
It would be helpful if Twinkle popped up a warning if you try to report a user to UAA or AIV when they're already blocked - I've made that mistake a few times. It's not a critical issue, since I'm pretty sure a bot will come along and clean up the filing, but it would be nice to have.

**Comment by DannyS712** [comment]
Should be pretty straight forward. Coding now. Do you want a warning shown if the user is only partially blocked?

**Comment by creffett** [comment]
Good question - my gut reaction is that the kind of editors getting reported to UAA/AIV probably aren't the kind who already have partial blocks applied to them under the current policy, so probably not a ton of overlap. Might as well show it for partial blocks initially.
