### ISSUE TITLE
Failed to list a soft redirect at RFD

### ISSUE THREAD

**Issue by evad37** [azatoth/twinkle#861]
See the [history of Megathread](https://en.wikipedia.org/w/index.php?title=Megathread&action=history) and [the talk page](https://en.wikipedia.org/wiki/Talk:Megathread), and  [JzG's contributions for 11 Feb](https://en.wikipedia.org/w/index.php?target=JzG&namespace=all&tagfilter=&start=2020-02-11&end=2020-02-11&limit=50&title=Special%3AContributions). It seems Twinkle tried to list the discussion on a nonexistent subpage [[Wikipedia:Redirects for discussion/Log/NaN undefined NaN]] - it didn't create that page, but did add the nomination template with that link in the edit summary, and the same with the author notification. After adding a fake #REDIRECT to the page Twinkle worked as expected.

**Comment by Amorymeltzer** [comment]
Thanks for the report @evad37: I've got a fix for this, and another issue I discovered while testing it coming up soon.
