### ISSUE TITLE
Update graphical control elements in all modules

### ISSUE THREAD

**Issue by c16u** [azatoth/twinkle#903]
Update all graphical control elements in all modules to reflect the modern design employed throughout Wikipedia such as in [Special:Preferences](https://en.wikipedia.org/wiki/Special:Preferences). Elements to update include but are not limited to:

- Dropdowns
- Text boxes
- Radio buttons
- Checkboxes
- Buttons
- Tooltips

**Comment by Amorymeltzer** [comment]
That's basically what #414 is, although honestly I kind of expect the recent move to use vue more likely to happen.  It's a lot of work and a long way off, to say the least!

**Comment by Amorymeltzer** [comment]
In favor of #414
