### ISSUE TITLE
Twinkle tries to use PageCuration on files

### ISSUE THREAD

**Issue by AntiCompositeNumber** [azatoth/twinkle#932]
There is no Page Curation available for files, but Twinkle still tries to mark pages as curated:
```
Tagging file: completed (File:Williams Lost Highway Playbill.jpg)
Marking page as curated: The page specified does not exist in pagetriage queue
```
Ye Olde patrolling should be used instead.

**Comment by Amorymeltzer** [comment]
The error is what #930 was attempting to solve, although you're quite right that trying to triage inappropriate namespaces is a totally separate issue (although would have been resolved by #930).  I've now updated that to fall back to patrol on inproper namespaces.
