### ISSUE TITLE
{{copyvio}} tagging

### ISSUE THREAD

**Issue by TannerFilip** [azatoth/twinkle#97]
{{copyvio}} tagging might be a good feature, it'd certainly make tagging copyright violations easier. Choose a section, or full page, enter URL, it reports to the dates' page and warns the user if the addition was within x days.

**Comment by Amorymeltzer** [comment]
We _could_ add this to the tag module with some limited functionality (e.g., probably not inputs for four sets of ranges) but we'd have to treat it differently than the others (e.g. not placed in `{{mi}}`).  Notification is currently enabled for one template only but we could expand that to this case (although honestly it seems overkill here).

It's an odd fit here, so is it worth doing?  It'd be a less effective version of @enterprisey's [User:Enterprisey/cv-revdel](https://en.wikipedia.org/wiki/User:Enterprisey/cv-revdel) but would probably be sufficient for the average passing user.

**Comment by Amorymeltzer** [comment]
I'm disinclined toward adding this.  While clearly it'd be useful to some, by all accounts it is only used a couple times a day.  Presumably that'd grow if added to Twinkle, but it also doesn't really fit in with most of the rest of the available tags.  Not only is this a content-altering tag, but it's a fairly unique process that many are unlikely to be familiar with.  The most similar item is to PNT, but again, this would be a content-blanking notice among a sea of actual tags.

**Comment by DannyS712** [comment]
Given the creation of [cv-revdel](https://en.wikipedia.org/wiki/User:Enterprisey/cv-revdel), I agree that this isn't needed

**Comment by siddharthvp** [comment]
cv-revdel script doesn't support {{copyvio}} tagging. Not that I intend to
work on this though...
