### ISSUE TITLE
Using {{multiple issues}} for only two issues, and how mobile Web browsers react to this

### ISSUE THREAD

**Issue by unforgettableid** [azatoth/twinkle#979]
Hi! When you use Twinkle to tag a page with two issues, it defaults to using {{multiple issues}}. I think that using {{multiple issues}} for only two issues isn't a very good idea.

Why?

Because, in mobile Web browsers, {{multiple issues}} doesn't tell readers what the issues actually are unless they click through in order to find out.

My proposed solution:  Twinkle should only ever add {{multiple issues}} when there are _three_ or more issues.

P.S.  Thank you very much for helping to maintain Twinkle!

**Comment by Amorymeltzer** [comment]
Truth be told that's my preference as well, but it was changed in https://github.com/azatoth/twinkle/pull/471#issuecomment-450493193 specifically to fit with the guidelines for mobile pages: https://www.mediawiki.org/wiki/Recommendations_for_mobile_friendly_articles_on_Wikimedia_wikis#Collapse_issues_with_a_multiple_issues_template.  The idea is that one collapsible template takes up less space than two uncollapsed templates.

**Comment by unforgettableid** [comment]
@jdlrobson:  Hi!

You wrote the above recommendation, [two years ago](https://www.mediawiki.org/w/index.php?title=Recommendations_for_mobile_friendly_articles_on_Wikimedia_wikis&diff=prev&oldid=2840495#Collapse_issues_with_a_multiple_issues_template).  It's a bit vague, though.

A.)  When you wrote "more options to mobile friendly skins", what did you mean by "more options"?

B.)  And nowadays, with the nice big device screens of today, do you still believe that two individual issues are too much?

**Comment by jdlrobson** [comment]
If you use multiple issues template on mobile then all issues are shown together in the overlay that opens. If you don't the user has to click multiple things to get an overview of the issues on the article. For some skins (e.g. not Minerva Wikimedia) there is no JavaScript enhancement and issues can easily take up the entire page. Thus I still stand by the recommendation that these should be grouped together semantically.
